/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05UAJ4398T#/functions/create_project",
  title: "Create a project",
  input_parameters: {
    properties: {
      project_name: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Project name",
      },
      company_name: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Client name",
      },
      description: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Description",
      },
      owner: {
        type: Schema.types.string,
        description: "Select owner of the project",
        title: "Owner",
      },
      due_date: { type: Schema.slack.types.timestamp, title: "Due on" },
      project_type: {
        type: Schema.types.string,
        title: "Project type",
        enum: ["RFP", "RFI", "DDQ", "SQ", "PP", "OTHER"],
      },
    },
    required: [
      "project_name",
      "company_name",
      "owner",
      "due_date",
      "project_type",
    ],
  },
  output_parameters: {
    properties: {
      project_id: { type: Schema.types.string, title: "Project ID" },
      project_name: { type: Schema.types.string, title: "Project name" },
      description: { type: Schema.types.string, title: "Description" },
      created_date: {
        type: Schema.types.string,
        description: "The datetime the project is created on",
        title: "Created on",
      },
      due_date: {
        type: Schema.types.string,
        description: "The datetime the project is due on",
        title: "Due on",
      },
      status: { type: Schema.types.string, title: "Status" },
      company_name: { type: Schema.types.string, title: "Client name" },
      owner: { type: Schema.types.string, title: "Owner" },
      creator: { type: Schema.types.string, title: "Creator" },
    },
    required: [
      "project_id",
      "project_name",
      "created_date",
      "due_date",
      "status",
      "company_name",
      "owner",
      "creator",
    ],
  },
});
