/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { ConnectorDefinition } from "../../connectors.ts";
import { Schema } from "../../deps.ts";

export default new ConnectorDefinition({
  callback_id: "A04T6GE3LEB#/functions/create_issue",
  source_file: "",
  title: "Jira Cloud - Create an Issue",
  description:
    "Create an issue in a Jira Cloud instance right from Slack. Does not support Jira Server.",
  input_parameters: {
    properties: {
      atlassian_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Atlassian Access Token",
      },
      jira_domain: { type: Schema.types.string, title: "Jira Domain" },
      project: { type: Schema.types.string, title: "Project" },
      summary: {
        type: Schema.types.string,
        description: "Summary of the bug or issue to create.",
        title: "Summary",
      },
      description: {
        type: Schema.types.string,
        description: "Description of the bug or issue to create.",
        title: "Description",
      },
      issueType: {
        type: Schema.types.string,
        description:
          "Type of issue to create: Bug, Improvement, New Feature, or Epic.",
        title: "Issue Type",
      },
    },
    required: [],
  },
  output_parameters: {
    properties: {
      issue_key: { type: Schema.types.string, title: "Issue Key" },
    },
    required: [],
  },
});
