/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateIssue from "./functions/create_issue.ts";
import EditIssue from "./functions/edit_issue.ts";

const JiraCloud = { functions: { CreateIssue, EditIssue } } as const;

export default JiraCloud;
