/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05UBDPKYP8#/functions/create_page",
  title: "Create a page",
  input_parameters: {
    properties: {
      microsoft_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Microsoft credential to use",
        title: "Microsoft access token",
      },
      title: {
        type: Schema.types.string,
        description: "Enter title",
        title: "Title",
      },
      content: {
        type: Schema.slack.types.rich_text,
        description: "Enter content",
        title: "Content",
      },
    },
    required: ["microsoft_access_token", "title", "content"],
  },
  output_parameters: {
    properties: {
      response_code: { type: Schema.types.string, title: "Response code" },
      title: { type: Schema.types.string, title: "Title" },
      onenote_web_url: { type: Schema.types.string, title: "Web URL" },
    },
    required: ["response_code", "title"],
  },
});
