/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05QNBAB4UA#/functions/copy_file",
  title: "Copy a file",
  input_parameters: {
    properties: {
      box_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Box Access Token",
      },
      file_id: {
        type: Schema.types.string,
        description: "Pick a file to copy",
        title: "File to copy",
      },
      parent_folder_id: {
        type: Schema.types.string,
        description: "Select a folder",
        title: "Destination folder",
      },
      name: {
        type: Schema.types.string,
        description: "Enter a new name",
        title: "Name",
      },
    },
    required: ["box_access_token", "file_id"],
  },
  output_parameters: {
    properties: {
      id: { type: Schema.types.string, title: "File ID" },
      web_link: { type: Schema.types.string, title: "File URL" },
    },
    required: ["id", "web_link"],
  },
});
