/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CopyFile from "./copy_file.ts";

Deno.test("CopyFile can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CopyFile_slack_function",
    title: "Test CopyFile",
    description: "This is a generated test to test CopyFile",
  });
  testWorkflow.addStep(CopyFile, { box_access_token: "test", file_id: "test" });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05QNBAB4UA#/functions/copy_file");
  assertEquals(actual.inputs, { box_access_token: "test", file_id: "test" });
});

Deno.test("All outputs of Slack function CopyFile should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CopyFile_slack_function",
    title: "Test CopyFile",
    description: "This is a generated test to test CopyFile",
  });
  const step = testWorkflow.addStep(CopyFile, {
    box_access_token: "test",
    file_id: "test",
  });
  assertExists(step.outputs.id);
  assertExists(step.outputs.web_link);
});
