/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateFolder from "./create_folder.ts";

Deno.test("CreateFolder can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateFolder_slack_function",
    title: "Test CreateFolder",
    description: "This is a generated test to test CreateFolder",
  });
  testWorkflow.addStep(CreateFolder, {
    box_access_token: "test",
    name: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05QNBAB4UA#/functions/create_folder");
  assertEquals(actual.inputs, { box_access_token: "test", name: "test" });
});

Deno.test("All outputs of Slack function CreateFolder should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateFolder_slack_function",
    title: "Test CreateFolder",
    description: "This is a generated test to test CreateFolder",
  });
  const step = testWorkflow.addStep(CreateFolder, {
    box_access_token: "test",
    name: "test",
  });
  assertExists(step.outputs.id);
  assertExists(step.outputs.web_link);
});
