/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05Q8KLHEHJ#/functions/merge_pull_request",
  title: "Merge pull request",
  input_parameters: {
    properties: {
      workspace: {
        type: Schema.types.string,
        description: "Enter Bitbucket workspace",
        title: "Bitbucket workspace",
      },
      repo_slug: {
        type: Schema.types.string,
        description: "Enter repository name",
        title: "Repository",
      },
      pull_request_id: {
        type: Schema.types.string,
        description: "Enter a pull request ID",
        title: "Pull request ID",
      },
      message: {
        type: Schema.types.string,
        description: "Enter a message",
        title: "Message",
      },
      close_source_branch: {
        type: Schema.types.boolean,
        description: "Enter Close Source Branch",
        title: "Close Source Branch",
      },
      merge_strategy: {
        type: Schema.types.string,
        description: "Enter merge strategy",
        title: "Merge strategy",
        enum: ["merge_commit", "squash", "fast_forward"],
      },
      bitbucket_access_token: {
        type: Schema.slack.types.oauth2,
        title: "bitbucket access token",
      },
    },
    required: [
      "workspace",
      "repo_slug",
      "pull_request_id",
      "bitbucket_access_token",
    ],
  },
  output_parameters: {
    properties: {
      response: { type: Schema.types.string, title: "Response code" },
      workspace: { type: Schema.types.string, title: "Bitbucket workspace ID" },
      repo_slug: { type: Schema.types.string, title: "Repository ID" },
      pull_request_id: {
        type: Schema.types.string,
        description: "ID of the pull request to be merged",
        title: "Pull request ID",
      },
    },
    required: [],
  },
});
