/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateAlert from "./create_alert.ts";

Deno.test("CreateAlert can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateAlert_slack_function",
    title: "Test CreateAlert",
    description: "This is a generated test to test CreateAlert",
  });
  testWorkflow.addStep(CreateAlert, { source: "test", summary: "test" });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05TUC2EWBA#/functions/create_alert");
  assertEquals(actual.inputs, { source: "test", summary: "test" });
});

Deno.test("All outputs of Slack function CreateAlert should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateAlert_slack_function",
    title: "Test CreateAlert",
    description: "This is a generated test to test CreateAlert",
  });
  const step = testWorkflow.addStep(CreateAlert, {
    source: "test",
    summary: "test",
  });
  assertExists(step.outputs.alert_id);
});
