/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateCause from "./create_cause.ts";

Deno.test("CreateCause can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateCause_slack_function",
    title: "Test CreateCause",
    description: "This is a generated test to test CreateCause",
  });
  testWorkflow.addStep(CreateCause, { name: "test" });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05TUC2EWBA#/functions/create_cause");
  assertEquals(actual.inputs, { name: "test" });
});

Deno.test("All outputs of Slack function CreateCause should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateCause_slack_function",
    title: "Test CreateCause",
    description: "This is a generated test to test CreateCause",
  });
  const step = testWorkflow.addStep(CreateCause, { name: "test" });
  assertExists(step.outputs.cause_id);
});
