/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import UpdateCause from "./update_cause.ts";

Deno.test("UpdateCause can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UpdateCause_slack_function",
    title: "Test UpdateCause",
    description: "This is a generated test to test UpdateCause",
  });
  testWorkflow.addStep(UpdateCause, { cause_id: "test" });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05TUC2EWBA#/functions/update_cause");
  assertEquals(actual.inputs, { cause_id: "test" });
});

Deno.test("All outputs of Slack function UpdateCause should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UpdateCause_slack_function",
    title: "Test UpdateCause",
    description: "This is a generated test to test UpdateCause",
  });
  const step = testWorkflow.addStep(UpdateCause, { cause_id: "test" });
  assertExists(step.outputs.cause_id);
  assertExists(step.outputs.name);
  assertExists(step.outputs.description);
  assertExists(step.outputs.position);
});
