/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import StartWorkflow from "./start_workflow.ts";

Deno.test("StartWorkflow can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_StartWorkflow_slack_function",
    title: "Test StartWorkflow",
    description: "This is a generated test to test StartWorkflow",
  });
  testWorkflow.addStep(StartWorkflow, {
    workflow_id: "test",
    user_context: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A07T6LETA9Z#/functions/start_workflow");
  assertEquals(actual.inputs, { workflow_id: "test", user_context: "test" });
});

Deno.test("All outputs of Slack function StartWorkflow should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_StartWorkflow_slack_function",
    title: "Test StartWorkflow",
    description: "This is a generated test to test StartWorkflow",
  });
  const step = testWorkflow.addStep(StartWorkflow, {
    workflow_id: "test",
    user_context: "test",
  });
  assertExists(step.outputs.success);
  assertExists(step.outputs.workflow_instance_id);
});
