/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import UpdateTicket from "./update_ticket.ts";

Deno.test("UpdateTicket can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UpdateTicket_slack_function",
    title: "Test UpdateTicket",
    description: "This is a generated test to test UpdateTicket",
  });
  testWorkflow.addStep(UpdateTicket, {
    user_context: "test",
    inbox_id: "test",
    ticket_id: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A07T6LETA9Z#/functions/update_ticket");
  assertEquals(actual.inputs, {
    user_context: "test",
    inbox_id: "test",
    ticket_id: "test",
  });
});

Deno.test("All outputs of Slack function UpdateTicket should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UpdateTicket_slack_function",
    title: "Test UpdateTicket",
    description: "This is a generated test to test UpdateTicket",
  });
  const step = testWorkflow.addStep(UpdateTicket, {
    user_context: "test",
    inbox_id: "test",
    ticket_id: "test",
  });
  assertExists(step.outputs.ticket_id);
  assertExists(step.outputs.ticket_name);
  assertExists(step.outputs.ticket_number);
  assertExists(step.outputs.ticket_description);
  assertExists(step.outputs.slack_message_url);
  assertExists(step.outputs.priority);
  assertExists(step.outputs.status);
  assertExists(step.outputs.inbox_id);
  assertExists(step.outputs.date_created);
});
