/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import AddTimeOffRequest from "./functions/add_time_off_request.ts";
import CreateContract from "./functions/create_contract.ts";

const Deel = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/deel/add_time_off_request AddTimeOffRequest} documentation.
     */
    AddTimeOffRequest,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/deel/create_contract CreateContract} documentation.
     */
    CreateContract,
  },
} as const;

export default Deel;
