/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CommentOnAFolder from "./functions/comment_on_a_folder.ts";
import CommentOnATask from "./functions/comment_on_a_task.ts";
import CreateAFolder from "./functions/create_a_folder.ts";
import CreateATask from "./functions/create_a_task.ts";
import UpdateATask from "./functions/update_a_task.ts";

const Wrike = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/wrike/comment_on_a_folder CommentOnAFolder} documentation.
     */
    CommentOnAFolder,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/wrike/comment_on_a_task CommentOnATask} documentation.
     */
    CommentOnATask,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/wrike/create_a_folder CreateAFolder} documentation.
     */
    CreateAFolder,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/wrike/create_a_task CreateATask} documentation.
     */
    CreateATask,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/wrike/update_a_task UpdateATask} documentation.
     */
    UpdateATask,
  },
} as const;

export default Wrike;
