/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A061MGQNY2K#/functions/add_time_off_request",
  title: "Add a time off request",
  input_parameters: {
    properties: {
      deel_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Deel Credentials to use",
        title: "Deel Access Token",
      },
      contract_id: {
        type: Schema.types.string,
        description: "Select a contract",
        title: "Contract ID",
      },
      time_off_type: {
        type: Schema.types.string,
        description: "Select the time off type",
        title: "Time off type",
        enum: ["VACATION", "SICK_LEAVE", "OTHER"],
      },
      start_date: {
        type: Schema.slack.types.date,
        description: "Select the start date",
        title: "Start date",
      },
      end_date: {
        type: Schema.slack.types.date,
        description: "Select the end date",
        title: "End date",
      },
      reason: {
        type: Schema.types.string,
        description: "Enter a text",
        title: "Reason",
      },
      is_half_start_day: {
        type: Schema.types.boolean,
        title: "Is the start day a half day?",
      },
      is_half_end_day: {
        type: Schema.types.boolean,
        title: "Is the end day a half day?",
      },
      other_timeoff_name: {
        type: Schema.types.string,
        title: "Custom name for other time off",
      },
    },
    required: [
      "deel_access_token",
      "contract_id",
      "time_off_type",
      "start_date",
      "end_date",
    ],
  },
  output_parameters: {
    properties: {
      request_id: { type: Schema.types.string, title: "Time off request ID" },
      status: { type: Schema.types.string, title: "Request status" },
    },
    required: ["request_id", "status"],
  },
});
