/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A061MGQNY2K#/functions/create_contract",
  title: "Create a new contract",
  input_parameters: {
    properties: {
      deel_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Deel Credentials to use",
        title: "Deel Access Token",
      },
      title: {
        type: Schema.types.string,
        description: "Enter the title of the contract",
        title: "Title",
      },
      legal_entity_id: {
        type: Schema.types.string,
        description: "Select the legal entity",
        title: "Legal Entity",
      },
      team_id: {
        type: Schema.types.string,
        description: "Select the team",
        title: "Team",
      },
      job_title: {
        type: Schema.types.string,
        description: "Enter the job title",
        title: "Job title",
      },
      documents_required: {
        type: Schema.types.boolean,
        title: "Are documents required?",
      },
      contract_type: {
        type: Schema.types.string,
        description: "Select contract type",
        title: "Contract type",
        enum: [
          "pay_as_you_go_time_based",
          "payg_tasks",
          "payg_milestones",
          "ongoing_time_based",
        ],
      },
      start_date: {
        type: Schema.slack.types.date,
        description: "Enter Start Date",
        title: "Start Date",
      },
      amount: {
        type: Schema.types.number,
        description: "Enter the amount to be paid",
        title: "Amount",
      },
      currency_code: {
        type: Schema.types.string,
        description: "Select the currency",
        title: "Currency",
      },
      frequency: {
        type: Schema.types.string,
        title: "Scale of the invoice cycle",
        enum: [
          "weekly",
          "monthly",
          "biweekly",
          "semimonthly",
          "calendar-month",
        ],
      },
      cycle_end: {
        type: Schema.types.number,
        description: "Select a date between 1-31",
        title: "Date invoice cycle ends",
      },
      cycle_end_type: {
        type: Schema.types.string,
        title: "Select the cycle end type",
        enum: ["DAY_OF_WEEK", "DAY_OF_LAST_WEEK", "DAY_OF_MONTH"],
      },
      payment_due_type: {
        type: Schema.types.string,
        title: "Select the payment due type",
        enum: ["REGULAR", "WITHIN_MONTH"],
      },
      payment_due_days: {
        type: Schema.types.number,
        description: "Enter payment due days between 0-90",
        title: "Payment due days",
      },
      scale: {
        type: Schema.types.string,
        description: "Select the scale at which the amount is paid.",
        title: "Scale of the invoice cycle",
        enum: [
          "hourly",
          "weekly",
          "monthly",
          "biweekly",
          "semimonthly",
          "calendar-month",
        ],
      },
    },
    required: [
      "deel_access_token",
      "title",
      "legal_entity_id",
      "team_id",
      "job_title",
      "documents_required",
      "contract_type",
      "start_date",
      "currency_code",
      "frequency",
      "cycle_end",
      "cycle_end_type",
      "payment_due_type",
      "payment_due_days",
    ],
  },
  output_parameters: {
    properties: {
      contract_id: {
        type: Schema.types.string,
        description: "Contract ID",
        title: "Contract ID",
      },
      contract_url: {
        type: Schema.types.string,
        description: "Contract URL",
        title: "Contract URL",
      },
    },
    required: ["contract_id", "contract_url"],
  },
});
