/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../../deps.ts";
import { Schema } from "../../deps.ts";

export default DefineFunction({
  callback_id: "A04RSGH23L7#/functions/resolve_incident",
  source_file: "",
  title: "Resolve a Pagerduty Incident",
  description: "This step marks a Pagerduty Incident as resolved",
  input_parameters: {
    properties: {
      incident_id: {
        type: Schema.types.string,
        description: "Incident id",
        title: "Incident Id",
      },
      resolution_note: {
        type: Schema.types.string,
        description: "Resolution note",
        title: "Resolution note",
      },
      pagerduty_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Pagerduty access token",
        title: "PagerDuty access token",
      },
    },
    required: ["incident_id", "resolution_note", "pagerduty_access_token"],
  },
  output_parameters: {
    properties: {
      incident_id: {
        type: Schema.types.string,
        description: "Incident id",
        title: "Incident Id",
      },
      incident_url: {
        type: Schema.types.string,
        description: "Incident url",
        title: "Incident url",
      },
      status: {
        type: Schema.types.string,
        description: "Status",
        title: "Status",
      },
      resolution_note: {
        type: Schema.types.string,
        description: "Resolution note",
        title: "Resolution note",
      },
      last_status_change_by: {
        type: Schema.types.string,
        description: "Last status change by",
        title: "Last status change by",
      },
      last_status_change_at: {
        type: Schema.types.string,
        description: "Last status change at",
        title: "Last status change at",
      },
    },
    required: [
      "incident_id",
      "incident_url",
      "status",
      "resolution_note",
      "last_status_change_by",
      "last_status_change_at",
    ],
  },
});
