/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A04MG80N5CY#/functions/add_spreadsheet_row",
  title: "Add to spreadsheet",
  description: "Add a row to a Google Sheets spreadsheet",
  input_parameters: {
    properties: {
      spreadsheet_id: {
        type: Schema.types.string,
        description: "Select a spreadsheet",
        title: "Spreadsheet",
      },
      sheet_title: {
        type: Schema.types.string,
        description: "Select a sheet",
        title: "Sheet",
      },
      columns: {
        type: Schema.types.object,
        description: "Columns",
        title: "Columns",
      },
      google_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Which account should we use to write to the spreadsheet?",
        title: "Google Access Token",
      },
    },
    required: [
      "spreadsheet_id",
      "sheet_title",
      "columns",
      "google_access_token",
    ],
  },
  output_parameters: {
    properties: {
      spreadsheet_url: {
        type: Schema.types.string,
        description: "Spreadsheet URL",
        title: "Spreadsheet URL",
      },
      spreadsheet_id: {
        type: Schema.types.string,
        description: "Spreadsheet ID",
        title: "Spreadsheet ID",
      },
    },
    required: ["spreadsheet_url", "spreadsheet_id"],
  },
});
