/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import AddSpreadsheetRow from "./add_spreadsheet_row.ts";

Deno.test("AddSpreadsheetRow can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_AddSpreadsheetRow_slack_function",
    title: "Test AddSpreadsheetRow",
    description: "This is a generated test to test AddSpreadsheetRow",
  });
  testWorkflow.addStep(AddSpreadsheetRow, {
    spreadsheet_id: "test",
    sheet_title: "test",
    columns: "test",
    google_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(
    actual.function_id,
    "A04MG80N5CY#/functions/add_spreadsheet_row",
  );
  assertEquals(actual.inputs, {
    spreadsheet_id: "test",
    sheet_title: "test",
    columns: "test",
    google_access_token: "test",
  });
});

Deno.test("All outputs of Slack function AddSpreadsheetRow should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_AddSpreadsheetRow_slack_function",
    title: "Test AddSpreadsheetRow",
    description: "This is a generated test to test AddSpreadsheetRow",
  });
  const step = testWorkflow.addStep(AddSpreadsheetRow, {
    spreadsheet_id: "test",
    sheet_title: "test",
    columns: "test",
    google_access_token: "test",
  });
  assertExists(step.outputs.spreadsheet_url);
  assertExists(step.outputs.spreadsheet_id);
  assertExists(step.outputs.timestamp_started);
  assertExists(step.outputs.timestamp_completed);
});
