/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A04MG80N5CY#/functions/select_sheet",
  title: "Select a sheet",
  description: "Select a row in a Google Sheet",
  input_parameters: {
    properties: {
      spreadsheet_id: {
        type: Schema.types.string,
        description: "Select a spreadsheet",
        title: "Spreadsheet",
      },
      sheet_id: {
        type: Schema.types.string,
        description: "Select a sheet",
        title: "Sheet",
      },
      range: {
        type: Schema.types.string,
        description: "Select a range",
        title: "Choose a range to search",
      },
      google_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Which account should we use to access the spreadsheet?",
        title: "Google Access Token",
      },
    },
    required: ["spreadsheet_id", "sheet_id", "google_access_token"],
  },
  output_parameters: {
    properties: {
      values: {
        type: Schema.types.string,
        description: "Values",
        title: "Values",
      },
      spreadsheet_id: {
        type: Schema.types.string,
        description: "Spreadsheet ID",
        title: "Spreadsheet ID",
      },
      sheet_id: {
        type: Schema.types.string,
        description: "Sheet ID",
        title: "Sheet ID",
      },
      spreadsheet_url: {
        type: Schema.types.string,
        description: "Spreadsheet URL",
        title: "Spreadsheet URL",
      },
    },
    required: ["values", "spreadsheet_id", "sheet_id", "spreadsheet_url"],
  },
});
