/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import SelectSheet from "./select_sheet.ts";

Deno.test("SelectSheet can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_SelectSheet_slack_function",
    title: "Test SelectSheet",
    description: "This is a generated test to test SelectSheet",
  });
  testWorkflow.addStep(SelectSheet, {
    spreadsheet_id: "test",
    sheet_id: "test",
    google_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A04MG80N5CY#/functions/select_sheet");
  assertEquals(actual.inputs, {
    spreadsheet_id: "test",
    sheet_id: "test",
    google_access_token: "test",
  });
});

Deno.test("All outputs of Slack function SelectSheet should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_SelectSheet_slack_function",
    title: "Test SelectSheet",
    description: "This is a generated test to test SelectSheet",
  });
  const step = testWorkflow.addStep(SelectSheet, {
    spreadsheet_id: "test",
    sheet_id: "test",
    google_access_token: "test",
  });
  assertExists(step.outputs.values);
  assertExists(step.outputs.spreadsheet_id);
  assertExists(step.outputs.sheet_id);
  assertExists(step.outputs.spreadsheet_url);
});
