/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A04MG80N5CY#/functions/select_spreadsheet_row",
  title: "Select a spreadsheet row",
  description: "Select a row in a Google Sheet",
  input_parameters: {
    properties: {
      spreadsheet_id: {
        type: Schema.types.string,
        description: "Select a spreadsheet",
        title: "Spreadsheet",
      },
      sheet_title: {
        type: Schema.types.string,
        description: "Select a sheet",
        title: "Sheet",
      },
      column_name: {
        type: Schema.types.string,
        description: "Select a column",
        title: "Choose a column to search",
      },
      cell_value: {
        type: Schema.types.string,
        description: "Add a value",
        title: "Cell value to find",
      },
      google_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Which account should we use to access the spreadsheet?",
        title: "Google Access Token",
      },
    },
    required: [
      "spreadsheet_id",
      "sheet_title",
      "column_name",
      "cell_value",
      "google_access_token",
    ],
  },
  output_parameters: {
    properties: {
      column_values: { type: Schema.types.object, title: "Column values" },
      row_index: {
        type: Schema.types.string,
        description: "Row index",
        title: "Row index",
      },
    },
    required: ["column_values", "row_index"],
  },
});
