/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A04MG80N5CY#/functions/select_spreadsheet_rows",
  title: "Select spreadsheet rows",
  description: "Select rows from a Google Sheet",
  input_parameters: {
    properties: {
      spreadsheet_id: {
        type: Schema.types.string,
        description: "Select a spreadsheet",
        title: "Spreadsheet",
      },
      sheet_title: {
        type: Schema.types.string,
        description: "Select a sheet",
        title: "Sheet",
      },
      filter_condition: {
        type: Schema.types.object,
        description: "Filter criteria",
        title: "Filter criteria",
      },
      filter_operators: {
        type: Schema.types.object,
        description: "Filter operators",
        title: "Filter operators",
      },
      google_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Which account should we use to access the spreadsheet?",
        title: "Google Access Token",
      },
    },
    required: ["spreadsheet_id", "sheet_title", "google_access_token"],
  },
  output_parameters: {
    properties: {
      row_items: {
        type: Schema.types.array,
        title: "Row items",
        items: { type: Schema.types.string },
      },
      item_count: { type: Schema.types.integer, title: "Item count" },
      columns: { type: Schema.types.object, title: "Columns" },
      spreadsheet_url: {
        type: Schema.types.string,
        description: "Spreadsheet URL",
        title: "Spreadsheet URL",
      },
      timestamp_started: {
        type: Schema.slack.types.timestamp,
        description: "Time when step started",
        title: "Time when step started",
      },
      timestamp_completed: {
        type: Schema.slack.types.timestamp,
        description: "Time when step ended",
        title: "Time when step ended",
      },
    },
    required: [
      "row_items",
      "item_count",
      "columns",
      "spreadsheet_url",
      "timestamp_started",
      "timestamp_completed",
    ],
  },
});
