/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateIssue from "./create_issue.ts";

const Github = { CreateIssue } as const;

export default Github;
