/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import RestartBuild from "./restart_build.ts";

Deno.test("RestartBuild can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_RestartBuild_slack_function",
    title: "Test RestartBuild",
    description: "This is a generated test to test RestartBuild",
  });
  testWorkflow.addStep(RestartBuild, {
    repo_slug: "test",
    branch: "test",
    build_id: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A0619K2GN2W#/functions/restart_build");
  assertEquals(actual.inputs, {
    repo_slug: "test",
    branch: "test",
    build_id: "test",
  });
});

Deno.test("All outputs of Slack function RestartBuild should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_RestartBuild_slack_function",
    title: "Test RestartBuild",
    description: "This is a generated test to test RestartBuild",
  });
  const step = testWorkflow.addStep(RestartBuild, {
    repo_slug: "test",
    branch: "test",
    build_id: "test",
  });
  assertExists(step.outputs.build_id);
  assertExists(step.outputs.branch);
  assertExists(step.outputs.repository);
  assertExists(step.outputs.build_url);
});
