/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A0619K2GN2W#/functions/trigger_build",
  title: "Trigger build",
  input_parameters: {
    properties: {
      repo_slug: { type: Schema.types.string, title: "Repository" },
      branch: {
        type: Schema.types.string,
        description: "Select a branch",
        title: "Branch",
      },
      message: { type: Schema.types.string, title: "Message" },
    },
    required: ["repo_slug", "branch", "message"],
  },
  output_parameters: {
    properties: {
      request_id: { type: Schema.types.string, title: "Request ID" },
      request_message: { type: Schema.types.string, title: "Message" },
      branch: { type: Schema.types.string, title: "Branch" },
      repository: { type: Schema.types.string, title: "Repository" },
    },
    required: [],
  },
});
