/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { ConnectorDefinition } from "../../connectors.ts";
import { Schema } from "../../deps.ts";

export default new ConnectorDefinition({
  callback_id: "A04S9208DRQ#/functions/create_meeting",
  source_file: "",
  title: "Create a Zoom Meeting",
  description: "Create a Zoom meeting",
  input_parameters: {
    properties: {
      topic: {
        type: Schema.types.string,
        description: "Meeting topic",
        title: "Topic",
      },
      agenda: {
        type: Schema.types.string,
        description: "Agenda for the meeting",
        title: "Agenda",
      },
      invitees: {
        type: Schema.types.array,
        description: "Meeting Invitees",
        title: "Invitees",
        items: { type: Schema.slack.types.user_id },
      },
      start_time: {
        type: Schema.slack.types.timestamp,
        description: "Start time of the meeting",
        title: "Start Time",
      },
      zoom_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Zoom access token",
      },
    },
    required: [],
  },
  output_parameters: {
    properties: {
      meeting_id: {
        type: Schema.types.number,
        description: "Meeting Id",
        title: "Meeting Id",
      },
      topic: {
        type: Schema.types.string,
        description: "Topic of the meeting",
        title: "Topic",
      },
      start_time: {
        type: Schema.types.string,
        description: "Start time of the meeting",
        title: "Start Time",
      },
      host_email: {
        type: Schema.types.string,
        description: "Email of the meeting's host",
        title: "Host Email",
      },
      start_url: {
        type: Schema.types.string,
        description: "Start url",
        title: "Start url",
      },
      join_url: {
        type: Schema.types.string,
        description: "Join url",
        title: "Join url",
      },
      invitees: {
        type: Schema.types.array,
        description: "Meeting Invitees",
        title: "Invitees",
        items: { type: Schema.slack.types.user_id },
      },
      invitee_emails: {
        type: Schema.types.array,
        description: "Emails of the Invitees with comma separated",
        title: "Invitee emails",
        items: { type: Schema.types.string },
      },
    },
    required: [],
  },
});
