/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateMeeting from "./functions/create_meeting.ts";

const Zoom = { functions: { CreateMeeting } } as const;

export default Zoom;
