/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import AddSpreadsheetRow from "./functions/add_spreadsheet_row.ts";

const GoogleSheets = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/google.sheets/add_spreadsheet_row AddSpreadsheetRow} documentation.
     */
    AddSpreadsheetRow,
  },
} as const;

export default GoogleSheets;
