/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05RZA1NU7L#/functions/create_tasklist",
  title: "Create a task list",
  description: "Creates an empty list",
  input_parameters: {
    properties: {
      title: {
        type: Schema.types.string,
        description: "Enter a name",
        title: "List name",
      },
      google_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Whose account should be used to create the tasks?",
        title: "Google access token",
      },
    },
    required: ["title", "google_access_token"],
  },
  output_parameters: {
    properties: {
      title: { type: Schema.types.string, title: "Task title" },
      tasklist_id: { type: Schema.types.string, title: "Tasklist ID" },
    },
    required: ["title", "tasklist_id"],
  },
});
