/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateTasklist from "./create_tasklist.ts";

Deno.test("CreateTasklist can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateTasklist_slack_function",
    title: "Test CreateTasklist",
    description: "This is a generated test to test CreateTasklist",
  });
  testWorkflow.addStep(CreateTasklist, {
    title: "test",
    google_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05RZA1NU7L#/functions/create_tasklist");
  assertEquals(actual.inputs, { title: "test", google_access_token: "test" });
});

Deno.test("All outputs of Slack function CreateTasklist should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateTasklist_slack_function",
    title: "Test CreateTasklist",
    description: "This is a generated test to test CreateTasklist",
  });
  const step = testWorkflow.addStep(CreateTasklist, {
    title: "test",
    google_access_token: "test",
  });
  assertExists(step.outputs.title);
  assertExists(step.outputs.tasklist_id);
});
