/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05RZA1NU7L#/functions/insert_task",
  title: "Insert a task",
  input_parameters: {
    properties: {
      tasklist_id: {
        type: Schema.types.string,
        description: "Select a list",
        title: "List",
      },
      title: {
        type: Schema.types.string,
        description: "Enter task name",
        title: "Task",
      },
      notes: {
        type: Schema.types.string,
        description: "Add details",
        title: "Details",
      },
      due: {
        type: Schema.slack.types.timestamp,
        description: "Due date for the task",
        title: "Due on",
      },
      google_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Whose account should be creating the tasks?",
        title: "Google access token",
      },
    },
    required: ["tasklist_id", "title", "notes", "google_access_token"],
  },
  output_parameters: {
    properties: {
      title: { type: Schema.types.string, title: "Task title" },
      task_id: { type: Schema.types.string, title: "Task ID" },
      notes: { type: Schema.types.string, title: "Notes" },
      status: { type: Schema.types.string, title: "Status" },
    },
    required: ["title", "task_id", "notes", "status"],
  },
});
