/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateVirtualCard from "./create_virtual_card.ts";

Deno.test("CreateVirtualCard can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateVirtualCard_slack_function",
    title: "Test CreateVirtualCard",
    description: "This is a generated test to test CreateVirtualCard",
  });
  testWorkflow.addStep(CreateVirtualCard, {
    user_id: "test",
    card_name: "test",
    amount_limit: "test",
    interval: "test",
    ramp_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(
    actual.function_id,
    "A066PC9JKJ7#/functions/create_virtual_card",
  );
  assertEquals(actual.inputs, {
    user_id: "test",
    card_name: "test",
    amount_limit: "test",
    interval: "test",
    ramp_access_token: "test",
  });
});

Deno.test("All outputs of Slack function CreateVirtualCard should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateVirtualCard_slack_function",
    title: "Test CreateVirtualCard",
    description: "This is a generated test to test CreateVirtualCard",
  });
  const step = testWorkflow.addStep(CreateVirtualCard, {
    user_id: "test",
    card_name: "test",
    amount_limit: "test",
    interval: "test",
    ramp_access_token: "test",
  });
  assertExists(step.outputs.user_id);
  assertExists(step.outputs.deferred_task_id);
});
