/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import SuspendCard from "./suspend_card.ts";

Deno.test("SuspendCard can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_SuspendCard_slack_function",
    title: "Test SuspendCard",
    description: "This is a generated test to test SuspendCard",
  });
  testWorkflow.addStep(SuspendCard, {
    user_id: "test",
    card_id: "test",
    ramp_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A066PC9JKJ7#/functions/suspend_card");
  assertEquals(actual.inputs, {
    user_id: "test",
    card_id: "test",
    ramp_access_token: "test",
  });
});

Deno.test("All outputs of Slack function SuspendCard should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_SuspendCard_slack_function",
    title: "Test SuspendCard",
    description: "This is a generated test to test SuspendCard",
  });
  const step = testWorkflow.addStep(SuspendCard, {
    user_id: "test",
    card_id: "test",
    ramp_access_token: "test",
  });
  assertExists(step.outputs.deferred_task_id);
});
