/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A066PC9JKJ7#/functions/suspend_card",
  title: "Suspend a card",
  description:
    "Suspend a card so that it is locked from use. This action is reversible.",
  input_parameters: {
    properties: {
      user_id: {
        type: Schema.types.string,
        description: "Select a user",
        title: "User",
      },
      card_id: {
        type: Schema.types.string,
        description: "Select a card",
        title: "Card",
      },
      ramp_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Ramp Credential to use",
        title: "Ramp access token",
      },
    },
    required: ["user_id", "card_id", "ramp_access_token"],
  },
  output_parameters: {
    properties: {
      deferred_task_id: {
        type: Schema.types.string,
        title: "Deferred task ID",
      },
    },
    required: ["deferred_task_id"],
  },
});
