/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import TerminateCard from "./terminate_card.ts";

Deno.test("TerminateCard can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_TerminateCard_slack_function",
    title: "Test TerminateCard",
    description: "This is a generated test to test TerminateCard",
  });
  testWorkflow.addStep(TerminateCard, {
    user_id: "test",
    card_id: "test",
    ramp_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A066PC9JKJ7#/functions/terminate_card");
  assertEquals(actual.inputs, {
    user_id: "test",
    card_id: "test",
    ramp_access_token: "test",
  });
});

Deno.test("All outputs of Slack function TerminateCard should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_TerminateCard_slack_function",
    title: "Test TerminateCard",
    description: "This is a generated test to test TerminateCard",
  });
  const step = testWorkflow.addStep(TerminateCard, {
    user_id: "test",
    card_id: "test",
    ramp_access_token: "test",
  });
  assertExists(step.outputs.deferred_task_id);
});
