/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05ULH1PNMA#/functions/create_issue",
  title: "Create an issue",
  input_parameters: {
    properties: {
      team_id: {
        type: Schema.types.string,
        description: "Select a team",
        title: "Team",
      },
      project_id: {
        type: Schema.types.string,
        description: "Select a project",
        title: "Project",
      },
      title: {
        type: Schema.types.string,
        description: "Enter title of the issue",
        title: "Title",
      },
      description: {
        type: Schema.types.string,
        description: "Enter description of the issue",
        title: "Description",
      },
      assignee_id: {
        type: Schema.types.string,
        description: "Select an assignee",
        title: "Assignee",
      },
      state_id: {
        type: Schema.types.string,
        description: "Select issue state",
        title: "State",
      },
      linear_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Linear access token",
      },
    },
    required: ["team_id", "title", "description", "linear_access_token"],
  },
  output_parameters: {
    properties: {
      issue_id: {
        type: Schema.types.string,
        description: "Id of the issue",
        title: "Issue ID",
      },
      title: {
        type: Schema.types.string,
        description: "Title of the issue",
        title: "Title",
      },
      description: {
        type: Schema.types.string,
        description: "Description of the issue",
        title: "Description",
      },
      assignee_email: { type: Schema.types.string, title: "Assignee email" },
      state: { type: Schema.types.string, title: "State" },
      url: { type: Schema.types.string, title: "URL" },
    },
    required: [],
  },
});
