/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05P4475DFY#/functions/create_document",
  title: "Create a document",
  input_parameters: {
    properties: {
      document_title: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Document title",
      },
      google_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Whose account should be creating document?",
        title: "Google access token",
      },
    },
    required: ["document_title", "google_access_token"],
  },
  output_parameters: {
    properties: {
      title: {
        type: Schema.types.string,
        description: "Document title",
        title: "Document title",
      },
      document_id: {
        type: Schema.types.string,
        description: "Document ID",
        title: "Document ID",
      },
      document_url: {
        type: Schema.types.string,
        description: "Document URL",
        title: "Document URL",
      },
    },
    required: ["title", "document_id", "document_url"],
  },
});
