/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05P4475DFY#/functions/select_document",
  title: "Select and retrieve a document",
  input_parameters: {
    properties: {
      document_id: {
        type: Schema.types.string,
        description: "Select a document",
        title: "Document title",
      },
      google_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Whose account should be fetching the document?",
        title: "Google access token",
      },
    },
    required: ["document_id", "google_access_token"],
  },
  output_parameters: {
    properties: {
      document_info: {
        type: Schema.types.object,
        description: "Document information",
        title: "Document information",
      },
    },
    required: ["document_info"],
  },
});
