/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateIssue from "./functions/create_issue.ts";
import MergePullRequest from "./functions/merge_pull_request.ts";

const AtlassianBitbucket = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/atlassian.bitbucket/create_issue CreateIssue} documentation.
     */
    CreateIssue,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/atlassian.bitbucket/merge_pull_request MergePullRequest} documentation.
     */
    MergePullRequest,
  },
} as const;

export default AtlassianBitbucket;
