/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05SUU730P2#/functions/archive_page",
  title: "Archive a page",
  input_parameters: {
    properties: {
      notion_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Notion access token",
      },
      page_id: {
        type: Schema.types.string,
        description: "Select page",
        title: "Page ID",
      },
    },
    required: ["page_id"],
  },
  output_parameters: {
    properties: {
      page_id: { type: Schema.types.string, title: "Page ID" },
      page_url: { type: Schema.types.string, title: "Page URL" },
    },
    required: ["page_id", "page_url"],
  },
});
