/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreatePage from "./create_page.ts";

Deno.test("CreatePage can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreatePage_slack_function",
    title: "Test CreatePage",
    description: "This is a generated test to test CreatePage",
  });
  testWorkflow.addStep(CreatePage, {
    parent_page_id: "test",
    page_title: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05SUU730P2#/functions/create_page");
  assertEquals(actual.inputs, { parent_page_id: "test", page_title: "test" });
});

Deno.test("All outputs of Slack function CreatePage should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreatePage_slack_function",
    title: "Test CreatePage",
    description: "This is a generated test to test CreatePage",
  });
  const step = testWorkflow.addStep(CreatePage, {
    parent_page_id: "test",
    page_title: "test",
  });
  assertExists(step.outputs.page_id);
  assertExists(step.outputs.page_url);
});
