/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateWorkspace from "./functions/create_workspace.ts";
import DuplicateForm from "./functions/duplicate_form.ts";
import GetForm from "./functions/get_form.ts";
import GetFormInsights from "./functions/get_form_insights.ts";

const Typeform = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/typeform/create_workspace CreateWorkspace} documentation.
     */
    CreateWorkspace,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/typeform/duplicate_form DuplicateForm} documentation.
     */
    DuplicateForm,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/typeform/get_form GetForm} documentation.
     */
    GetForm,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/typeform/get_form_insights GetFormInsights} documentation.
     */
    GetFormInsights,
  },
} as const;

export default Typeform;
