/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import SendEmail from "./functions/send_email.ts";

const MicrosoftOutlookEmail = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/microsoft.outlook.email/send_email SendEmail} documentation.
     */
    SendEmail,
  },
} as const;

export default MicrosoftOutlookEmail;
