/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CopySurvey from "./functions/copy_survey.ts";
import CopySurveyFromTemplate from "./functions/copy_survey_from_template.ts";

const Surveymonkey = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/surveymonkey/copy_survey CopySurvey} documentation.
     */
    CopySurvey,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/surveymonkey/copy_survey_from_template CopySurveyFromTemplate} documentation.
     */
    CopySurveyFromTemplate,
  },
} as const;

export default Surveymonkey;
