/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateInterview from "./create_interview.ts";

Deno.test("CreateInterview can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateInterview_slack_function",
    title: "Test CreateInterview",
    description: "This is a generated test to test CreateInterview",
  });
  testWorkflow.addStep(CreateInterview, {
    opportunity_id: "test",
    perform_as: "test",
    panel_id: "test",
    date: "test",
    duration: "test",
    interviewers: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A063ZSXC719#/functions/create_interview");
  assertEquals(actual.inputs, {
    opportunity_id: "test",
    perform_as: "test",
    panel_id: "test",
    date: "test",
    duration: "test",
    interviewers: "test",
  });
});

Deno.test("All outputs of Slack function CreateInterview should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateInterview_slack_function",
    title: "Test CreateInterview",
    description: "This is a generated test to test CreateInterview",
  });
  const step = testWorkflow.addStep(CreateInterview, {
    opportunity_id: "test",
    perform_as: "test",
    panel_id: "test",
    date: "test",
    duration: "test",
    interviewers: "test",
  });
  assertExists(step.outputs.interview_id);
  assertExists(step.outputs.interview_url);
});
