/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A063ZSXC719#/functions/create_opportunity",
  title: "Create an opportunity",
  input_parameters: {
    properties: {
      perform_as: {
        type: Schema.types.string,
        description: "Please select an option",
        title: "Perform this create on behalf of a specified user",
      },
      name: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Contact full name",
      },
      headline: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Contact headline",
      },
      emails: {
        type: Schema.types.array,
        description: "Enter text",
        title: "Contact emails",
        items: { type: Schema.types.string },
      },
      origin: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Origin",
        enum: [
          "agency",
          "private",
          "internal",
          "referred",
          "sourced",
          "university",
        ],
      },
    },
    required: ["perform_as", "name"],
  },
  output_parameters: {
    properties: {
      opportunity_id: {
        type: Schema.types.string,
        description: "New opportunity ID",
        title: "Opportunity ID",
      },
      opportunity_url: {
        type: Schema.types.string,
        description: "New opportunity url",
        title: "Opportunity URL",
      },
    },
    required: ["opportunity_id"],
  },
});
