/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateEvent from "./functions/create_event.ts";

const MicrosoftOutlookCalendar = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/microsoft.outlook.calendar/create_event CreateEvent} documentation.
     */
    CreateEvent,
  },
} as const;

export default MicrosoftOutlookCalendar;
