/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateIgnore from "./functions/create_ignore.ts";

const Synk = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/synk/create_ignore CreateIgnore} documentation.
     */
    CreateIgnore,
  },
} as const;

export default Synk;
