/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateDocument from "./functions/create_document.ts";

const Lucid = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/lucid/create_document CreateDocument} documentation.
     */
    CreateDocument,
  },
} as const;

export default Lucid;
