/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import UnverifyCard from "./unverify_card.ts";

Deno.test("UnverifyCard can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UnverifyCard_slack_function",
    title: "Test UnverifyCard",
    description: "This is a generated test to test UnverifyCard",
  });
  testWorkflow.addStep(UnverifyCard, {
    card_id: "test",
    guru_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05RT1HSRRU#/functions/unverify_card");
  assertEquals(actual.inputs, { card_id: "test", guru_access_token: "test" });
});

Deno.test("All outputs of Slack function UnverifyCard should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UnverifyCard_slack_function",
    title: "Test UnverifyCard",
    description: "This is a generated test to test UnverifyCard",
  });
  const step = testWorkflow.addStep(UnverifyCard, {
    card_id: "test",
    guru_access_token: "test",
  });
  assertExists(step.outputs.card_id);
});
