/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import VerifyCard from "./verify_card.ts";

Deno.test("VerifyCard can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_VerifyCard_slack_function",
    title: "Test VerifyCard",
    description: "This is a generated test to test VerifyCard",
  });
  testWorkflow.addStep(VerifyCard, {
    card_id: "test",
    guru_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05RT1HSRRU#/functions/verify_card");
  assertEquals(actual.inputs, { card_id: "test", guru_access_token: "test" });
});

Deno.test("All outputs of Slack function VerifyCard should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_VerifyCard_slack_function",
    title: "Test VerifyCard",
    description: "This is a generated test to test VerifyCard",
  });
  const step = testWorkflow.addStep(VerifyCard, {
    card_id: "test",
    guru_access_token: "test",
  });
  assertExists(step.outputs.card_id);
});
