/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05TPV44YKG#/functions/add_contact",
  title: "Add a contact to audience",
  input_parameters: {
    properties: {
      mailchimp_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Mailchimp access token",
      },
      audience: {
        type: Schema.types.string,
        description: "Select audience",
        title: "Audience",
      },
      first_name: {
        type: Schema.types.string,
        description: "Enter text",
        title: "First name",
      },
      last_name: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Last name",
      },
      email: {
        type: Schema.types.string,
        description: "Enter email",
        title: "Email",
      },
    },
    required: [
      "mailchimp_access_token",
      "audience",
      "first_name",
      "last_name",
      "email",
    ],
  },
  output_parameters: {
    properties: {
      id: { type: Schema.types.string, title: "Contact ID" },
      full_name: { type: Schema.types.string, title: "Full name" },
      status: { type: Schema.types.string, title: "Status" },
    },
    required: [],
  },
});
