/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import AddContact from "./add_contact.ts";

Deno.test("AddContact can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_AddContact_slack_function",
    title: "Test AddContact",
    description: "This is a generated test to test AddContact",
  });
  testWorkflow.addStep(AddContact, {
    mailchimp_access_token: "test",
    audience: "test",
    first_name: "test",
    last_name: "test",
    email: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05TPV44YKG#/functions/add_contact");
  assertEquals(actual.inputs, {
    mailchimp_access_token: "test",
    audience: "test",
    first_name: "test",
    last_name: "test",
    email: "test",
  });
});

Deno.test("All outputs of Slack function AddContact should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_AddContact_slack_function",
    title: "Test AddContact",
    description: "This is a generated test to test AddContact",
  });
  const step = testWorkflow.addStep(AddContact, {
    mailchimp_access_token: "test",
    audience: "test",
    first_name: "test",
    last_name: "test",
    email: "test",
  });
  assertExists(step.outputs.id);
  assertExists(step.outputs.full_name);
  assertExists(step.outputs.status);
});
