/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05TPV44YKG#/functions/create_campaign",
  title: "Create an email campaign",
  input_parameters: {
    properties: {
      mailchimp_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Mailchimp access token",
      },
      campaign_title: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Campaign title",
      },
      subject_line: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Subject line",
      },
      preview_text: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Preview text",
      },
      from_name: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Who is sending this mail ?",
      },
      reply_to: {
        type: Schema.types.string,
        description: "Enter email",
        title: "Reply to address",
      },
      audience_id: {
        type: Schema.types.string,
        description: "Select audience",
        title: "Audience",
      },
    },
    required: [
      "mailchimp_access_token",
      "campaign_title",
      "subject_line",
      "preview_text",
      "from_name",
      "reply_to",
      "audience_id",
    ],
  },
  output_parameters: {
    properties: {
      id: { type: Schema.types.string, title: "Campaign ID" },
      status: { type: Schema.types.string, title: "Campaign status" },
      url: { type: Schema.types.string, title: "Campaign URL" },
    },
    required: [],
  },
});
