/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05TPV44YKG#/functions/send_campaign",
  title: "Send a Campaign",
  input_parameters: {
    properties: {
      mailchimp_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Mailchimp access token",
      },
      campaign_id: {
        type: Schema.types.string,
        description: "Select a campaign",
        title: "Campaign",
      },
    },
    required: ["mailchimp_access_token", "campaign_id"],
  },
  output_parameters: {
    properties: { response: { type: Schema.types.string, title: "Response" } },
    required: ["response"],
  },
});
