/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import SelectRecord from "./select_record.ts";

Deno.test("SelectRecord can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_SelectRecord_slack_function",
    title: "Test SelectRecord",
    description: "This is a generated test to test SelectRecord",
  });
  testWorkflow.addStep(SelectRecord, {
    base_id: "test",
    table_id: "test",
    search_column: "test",
    search_value: "test",
    airtable_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05UG04QC4X#/functions/select_record");
  assertEquals(actual.inputs, {
    base_id: "test",
    table_id: "test",
    search_column: "test",
    search_value: "test",
    airtable_access_token: "test",
  });
});

Deno.test("All outputs of Slack function SelectRecord should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_SelectRecord_slack_function",
    title: "Test SelectRecord",
    description: "This is a generated test to test SelectRecord",
  });
  const step = testWorkflow.addStep(SelectRecord, {
    base_id: "test",
    table_id: "test",
    search_column: "test",
    search_value: "test",
    airtable_access_token: "test",
  });
  assertExists(step.outputs.record);
  assertExists(step.outputs.record_id);
  assertExists(step.outputs.record_url);
});
