/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import RemoveTags from "./remove_tags.ts";

Deno.test("RemoveTags can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_RemoveTags_slack_function",
    title: "Test RemoveTags",
    description: "This is a generated test to test RemoveTags",
  });
  testWorkflow.addStep(RemoveTags, {
    ticket_id: "test",
    zendesk_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A0660D0LBV3#/functions/remove_tags");
  assertEquals(actual.inputs, {
    ticket_id: "test",
    zendesk_access_token: "test",
  });
});

Deno.test("All outputs of Slack function RemoveTags should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_RemoveTags_slack_function",
    title: "Test RemoveTags",
    description: "This is a generated test to test RemoveTags",
  });
  const step = testWorkflow.addStep(RemoveTags, {
    ticket_id: "test",
    zendesk_access_token: "test",
  });
  assertExists(step.outputs.ticket_id);
  assertExists(step.outputs.ticket_url);
  assertExists(step.outputs.status);
  assertExists(step.outputs.removed_tags);
});
