/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A0660D0LBV3#/functions/update_ticket",
  title: "Update a ticket",
  input_parameters: {
    properties: {
      ticket_id: {
        type: Schema.types.integer,
        description: "Enter ticket ID",
        title: "Ticket ID",
      },
      requester_email: {
        type: Schema.types.string,
        description: "Enter text",
        title: "New requester email",
      },
      assignee_id: { type: Schema.types.integer, title: "New assignee" },
      group_id: { type: Schema.types.integer, title: "New group" },
      add_followers: {
        type: Schema.types.array,
        description: "Enter internal agent emails to be added",
        title: "Add followers",
        items: { type: Schema.types.string },
      },
      remove_followers: {
        type: Schema.types.array,
        description: "Enter internal agent emails to be removed",
        title: "Remove followers",
        items: { type: Schema.types.string },
      },
      add_cc_emails: {
        type: Schema.types.array,
        description: "Enter external email CCs to be added",
        title: "Add email CCs",
        items: { type: Schema.types.string },
      },
      remove_cc_emails: {
        type: Schema.types.array,
        description: "Enter external email CCs to be removed",
        title: "Remove email CCs",
        items: { type: Schema.types.string },
      },
      subject: {
        type: Schema.types.string,
        description: "Enter text",
        title: "New ticket subject",
      },
      type: {
        type: Schema.types.string,
        title: "New ticket type",
        enum: ["problem", "incident", "question", "task"],
      },
      priority: {
        type: Schema.types.string,
        title: "New priority",
        enum: ["urgent", "high", "normal", "low"],
      },
      reply_type: {
        type: Schema.types.string,
        title: "Reply type",
        enum: ["true", "false"],
      },
      comment: {
        type: Schema.types.string,
        description: "Enter text",
        title: "New comment",
      },
      status: {
        type: Schema.types.string,
        title: "New status",
        enum: ["new", "open", "pending", "hold", "solved", "closed"],
      },
      zendesk_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Zendesk Credential to use",
        title: "Zendesk Access Token",
      },
    },
    required: ["ticket_id", "zendesk_access_token"],
  },
  output_parameters: {
    properties: {
      requester_id: {
        type: Schema.types.integer,
        description: "The ticket's requester ID",
        title: "Requester ID",
      },
      requester_email: {
        type: Schema.types.string,
        description: "The ticket's requester email",
        title: "Requester email",
      },
      ticket_id: {
        type: Schema.types.integer,
        description: "The ticket ID",
        title: "Ticket ID",
      },
      ticket_url: {
        type: Schema.types.string,
        description: "The ticket URL",
        title: "Ticket URL",
      },
      assignee_id: {
        type: Schema.types.integer,
        description: "ID for the assigned user",
        title: "Assignee ID",
      },
      priority: {
        type: Schema.types.string,
        description: "Priority of the ticket",
        title: "Priority",
      },
    },
    required: ["ticket_id", "ticket_url"],
  },
});
