/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateIssue from "./functions/create_issue.ts";
import UpdateIssue from "./functions/update_issue.ts";

const GithubCloud = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/github.cloud/create_issue CreateIssue} documentation.
     */
    CreateIssue,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/github.cloud/update_issue UpdateIssue} documentation.
     */
    UpdateIssue,
  },
} as const;

export default GithubCloud;
