/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import SelectDocument from "./functions/select_document.ts";

const GoogleDocs = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/google.docs/select_document SelectDocument} documentation.
     */
    SelectDocument,
  },
} as const;

export default GoogleDocs;
