/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../deps.ts";
import { Schema } from "../deps.ts";

export default DefineFunction({
  callback_id: "slack#/functions/add_channel_manager",
  source_file: "",
  title: "Add Channel Manager",
  description: "Add someone a channel manager.",
  input_parameters: {
    properties: {
      channel_id: {
        type: Schema.slack.types.channel_id,
        description: "Search all channels",
        title: "Select a channel",
      },
      user_ids: {
        type: Schema.types.array,
        description: "Search all people",
        title: "Select member(s)",
        items: { type: Schema.slack.types.user_id },
      },
    },
    required: ["channel_id", "user_ids"],
  },
  output_parameters: {
    properties: {
      user_ids: {
        type: Schema.types.array,
        description: "Person(s) who were made channel manager",
        title: "Person(s) who were made channel manager",
        items: { type: Schema.slack.types.user_id },
      },
    },
    required: [],
  },
});
