/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../../../functions/mod.ts";
import Schema.types from "../../schema_types.ts";
import Schema.slack.types from "../schema_types.ts";

export default DefineFunction({callback_id: "slack#/functions/add_channel_manager",
source_file: "",
title: "Add Channel Manager",
description: "Add someone a channel manager.",
input_parameters: {properties: {channel_id: {type: SlackTypes.channel_id,
description: "Search all channels",
title: "Select a channel"},
user_ids: {type: SchemaTypes.array,
description: "Search all people",
title: "Select member(s)",
items: {type: SlackTypes.user_id}}},
required: ["channel_id","user_ids"]},
output_parameters: {properties: {user_ids: {type: SchemaTypes.array,
description: "Person(s) who were made channel manager",
title: "Person(s) who were made channel manager",
items: {type: SlackTypes.user_id}}},
required: []}});