/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../dev_deps.ts";
import { DefineWorkflow } from "../dev_deps.ts";
import { ManifestFunctionSchema } from "../dev_deps.ts";
import { Schema } from "../deps.ts";
import AddChannelManager from "./add_channel_manager.ts";

Deno.test("AddChannelManager generates valid FunctionManifest", () => {
  assertEquals(
    AddChannelManager.definition.callback_id,
    "slack#/functions/add_channel_manager",
  );
  const expected: ManifestFunctionSchema = {
    source_file: "",
    title: "Add Channel Manager",
    description: "Add someone a channel manager.",
    input_parameters: {
      properties: {
        channel_id: {
          type: Schema.slack.types.channel_id,
          description: "Search all channels",
          title: "Select a channel",
        },
        user_ids: {
          type: Schema.types.array,
          description: "Search all people",
          title: "Select member(s)",
          items: { type: Schema.slack.types.user_id },
        },
      },
      required: ["channel_id", "user_ids"],
    },
    output_parameters: {
      properties: {
        user_ids: {
          type: Schema.types.array,
          description: "Person(s) who were made channel manager",
          title: "Person(s) who were made channel manager",
          items: { type: Schema.slack.types.user_id },
        },
      },
      required: [],
    },
  };
  const actual = AddChannelManager.export();

  assertEquals(actual, expected);
});

Deno.test("AddChannelManager can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_AddChannelManager_slack_function",
    title: "Test AddChannelManager",
    description: "This is a generated test to test AddChannelManager",
  });
  testWorkflow.addStep(AddChannelManager, {
    channel_id: "test",
    user_ids: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "slack#/functions/add_channel_manager");
  assertEquals(actual.inputs, { channel_id: "test", user_ids: "test" });
});

Deno.test("All outputs of Slack function AddChannelManager should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_AddChannelManager_slack_function",
    title: "Test AddChannelManager",
    description: "This is a generated test to test AddChannelManager",
  });
  const step = testWorkflow.addStep(AddChannelManager, {
    channel_id: "test",
    user_ids: "test",
  });
  assertExists(step.outputs.user_ids);
});
