/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../deps.ts";
import { Schema } from "../deps.ts";

export default DefineFunction({
  callback_id: "slack#/functions/add_bookmark",
  source_file: "",
  title: "Add a bookmark to channel",
  description: "Automatically create a bookmark in a channel",
  input_parameters: {
    properties: {
      channel_id: {
        type: Schema.slack.types.channel_id,
        description: "Search all channels",
        title: "Select a channel",
      },
      name: {
        type: Schema.types.string,
        description: "Enter the bookmark name",
        title: "Bookmark name",
      },
      link: {
        type: Schema.types.string,
        description: "https://docs.acme.com",
        title: "Bookmark Link",
      },
    },
    required: ["channel_id", "name", "link"],
  },
  output_parameters: {
    properties: {
      channel_id: {
        type: Schema.slack.types.channel_id,
        description: "Channel",
        title: "Channel",
      },
      bookmark_name: {
        type: Schema.types.string,
        description: "Bookmark name",
        title: "Bookmark name",
      },
      bookmark_link: {
        type: Schema.types.string,
        description: "Bookmark link",
        title: "Bookmark link",
      },
    },
    required: ["channel_id", "bookmark_name", "bookmark_link"],
  },
});
