/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../deps.ts";
import { Schema } from "../deps.ts";

export default DefineFunction({
  callback_id: "slack#/functions/create_channel",
  source_file: "",
  title: "Create a channel",
  description: "Create a Slack channel",
  input_parameters: {
    properties: {
      channel_name: {
        type: Schema.types.string,
        description: "Enter a channel name",
        title: "Channel name",
      },
      user_ids: {
        type: Schema.types.array,
        description: "Search all people",
        title: "Select Channel Manager(s)",
        items: { type: Schema.slack.types.user_id },
      },
      is_private: {
        type: Schema.types.boolean,
        description: "Make this channel private",
        title: "Make channel private",
      },
    },
    required: ["channel_name"],
  },
  output_parameters: {
    properties: {
      channel_id: {
        type: Schema.slack.types.channel_id,
        description: "Channel name",
        title: "Channel name",
      },
      user_ids: {
        type: Schema.types.array,
        description: "Person(s) who were made channel manager",
        title: "Person(s) who were made channel manager",
        items: { type: Schema.slack.types.user_id },
      },
    },
    required: ["channel_id", "user_ids"],
  },
});
