/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../deps.ts";
import { Schema } from "../deps.ts";

export default DefineFunction({
  callback_id: "slack#/functions/delay",
  source_file: "",
  title: "Delay",
  description: "Pause the workflow for a set amount of time",
  input_parameters: {
    properties: {
      minutes_to_delay: {
        type: Schema.types.integer,
        description: "Enter number of minutes",
        title: "Delay for this many minutes",
      },
    },
    required: ["minutes_to_delay"],
  },
  output_parameters: { properties: {}, required: [] },
});
