/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../deps.ts";
import { Schema } from "../deps.ts";

export default DefineFunction({
  callback_id: "slack#/functions/invite_user_to_channel",
  source_file: "",
  title: "Invite to channel",
  description:
    "Invite someone to a channel. This will only work if this workflow created the channel.",
  input_parameters: {
    properties: {
      channel_ids: {
        type: Schema.types.array,
        description: "Search all channels",
        title: "Select channel(s)",
        items: { type: Schema.slack.types.channel_id },
      },
      user_ids: {
        type: Schema.types.array,
        description: "Search all people",
        title: "Select member(s)",
        items: { type: Schema.slack.types.user_id },
      },
    },
    required: ["channel_ids", "user_ids"],
  },
  output_parameters: {
    properties: {
      user_ids: {
        type: Schema.types.array,
        description: "Person(s) who were invited",
        title: "Person(s) who were invited",
        items: { type: Schema.slack.types.user_id },
      },
    },
    required: [],
  },
});
