/** This file was autogenerated on Fri Jun 09 2023. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import Salesforce from "./salesforce/mod.ts";
import Gitlab from "./gitlab/mod.ts";
import GoogleSheets from "./google.sheets/mod.ts";
import Calendly from "./calendly/mod.ts";
import GithubCloud from "./github.cloud/mod.ts";
import Pagerduty from "./pagerduty/mod.ts";
import Zoom from "./zoom/mod.ts";
import JiraCloud from "./jira.cloud/mod.ts";
import Giphy from "./giphy/mod.ts";

const Connectors = {
  Salesforce,
  Gitlab,
  GoogleSheets,
  Calendly,
  GithubCloud,
  Pagerduty,
  Zoom,
  JiraCloud,
  Giphy,
} as const;

export default Connectors;
