/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../deps.ts";
import { Schema } from "../deps.ts";

export default DefineFunction({
  callback_id: "slack#/functions/remove_user_from_usergroup",
  source_file: "",
  title: "Remove from a user group",
  description: "Remove someone from a user group",
  input_parameters: {
    properties: {
      usergroup_id: {
        type: Schema.slack.types.usergroup_id,
        description: "Search all user groups",
        title: "Select a user group",
      },
      user_ids: {
        type: Schema.types.array,
        description: "Search all people",
        title: "Select member(s)",
        items: { type: Schema.slack.types.user_id },
      },
    },
    required: ["usergroup_id", "user_ids"],
  },
  output_parameters: {
    properties: {
      usergroup_id: {
        type: Schema.slack.types.usergroup_id,
        description: "User group",
        title: "User group",
      },
    },
    required: [],
  },
});
