/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../deps.ts";
import { Schema } from "../deps.ts";

export default DefineFunction({
  callback_id: "slack#/functions/reply_in_thread",
  source_file: "",
  title: "Reply in thread",
  description: "Send a message in a thread",
  input_parameters: {
    properties: {
      message_context: {
        type: Schema.slack.types.message_context,
        description: "Select a message to reply to",
        title: "Select a message to reply to",
      },
      message: {
        type: Schema.slack.types.rich_text,
        description: "Add a reply",
        title: "Add a reply",
      },
      reply_broadcast: {
        type: Schema.types.boolean,
        description: "Also send to conversation",
        title: "Also send to conversation",
      },
      metadata: {
        type: Schema.types.object,
        description:
          "Metadata you post to Slack is accessible to any app or user who is a member of that workspace",
        title: "Message metadata",
        properties: {
          event_type: { type: Schema.types.string },
          event_payload: { type: Schema.types.object },
        },
        additionalProperties: true,
        required: ["event_type", "event_payload"],
      },
    },
    required: ["message_context", "message"],
  },
  output_parameters: {
    properties: {
      message_context: {
        type: Schema.slack.types.message_context,
        description: "Reference to the message sent",
        title: "Reference to the message sent",
      },
      message_link: {
        type: Schema.types.string,
        description: "Message link",
        title: "Message link",
      },
    },
    required: ["message_context", "message_link"],
  },
});
