/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../deps.ts";
import { Schema } from "../deps.ts";

export default DefineFunction({
  callback_id: "slack#/functions/send_dm",
  source_file: "",
  title: "Send a direct message",
  description: "Send a direct message to someone",
  input_parameters: {
    properties: {
      user_id: {
        type: Schema.slack.types.user_id,
        description: "Search all people",
        title: "Select a member",
      },
      message: {
        type: Schema.slack.types.rich_text,
        description: "Add a message",
        title: "Add a message",
      },
      interactive_blocks: {
        type: Schema.slack.types.blocks,
        description: "Button(s) to send with the message",
        title: "Button(s) to send with the message",
      },
    },
    required: ["user_id", "message"],
  },
  output_parameters: {
    properties: {
      message_timestamp: {
        type: Schema.slack.types.timestamp,
        description: "Message time stamp",
        title: "Message time stamp",
      },
      message_link: {
        type: Schema.types.string,
        description: "Message link",
        title: "Message link",
      },
      action: {
        type: Schema.types.object,
        description: "Button interactivity data",
        title: "Button interactivity data",
      },
      interactivity: {
        type: Schema.slack.types.interactivity,
        description: "Interactivity context",
        title: "interactivity",
      },
      message_context: {
        type: Schema.slack.types.message_context,
        description: "Reference to the message sent",
        title: "Reference to the message sent",
      },
    },
    required: ["message_timestamp", "message_link", "message_context"],
  },
});
