/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateTask from "./functions/create_task.ts";
import UpdateTask from "./functions/update_task.ts";

const Clickup = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/clickup/create_task CreateTask} documentation.
     */
    CreateTask,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/clickup/update_task UpdateTask} documentation.
     */
    UpdateTask,
  },
} as const;

export default Clickup;
