/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CopySurvey from "./copy_survey.ts";

Deno.test("CopySurvey can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CopySurvey_slack_function",
    title: "Test CopySurvey",
    description: "This is a generated test to test CopySurvey",
  });
  testWorkflow.addStep(CopySurvey, {
    surveymonkey_access_token: "test",
    survey_id: "test",
    title: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05U1HZ9XGF#/functions/copy_survey");
  assertEquals(actual.inputs, {
    surveymonkey_access_token: "test",
    survey_id: "test",
    title: "test",
  });
});

Deno.test("All outputs of Slack function CopySurvey should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CopySurvey_slack_function",
    title: "Test CopySurvey",
    description: "This is a generated test to test CopySurvey",
  });
  const step = testWorkflow.addStep(CopySurvey, {
    surveymonkey_access_token: "test",
    survey_id: "test",
    title: "test",
  });
  assertExists(step.outputs.id);
  assertExists(step.outputs.title);
  assertExists(step.outputs.url);
});
