/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05U1HZ9XGF#/functions/copy_survey_from_template",
  title: "Copy a survey from a template",
  input_parameters: {
    properties: {
      surveymonkey_access_token: {
        type: Schema.slack.types.oauth2,
        description: "SurveyMonkey Credential to use",
        title: "SurveyMonkey Access Token",
      },
      template_id: {
        type: Schema.types.string,
        description: "Select a template",
        title: "Survey template",
      },
      title: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Survey title",
      },
    },
    required: ["surveymonkey_access_token", "template_id", "title"],
  },
  output_parameters: {
    properties: {
      id: {
        type: Schema.types.string,
        description: "New survey ID",
        title: "Survey ID",
      },
      title: {
        type: Schema.types.string,
        description: "New survey title",
        title: "Survey title",
      },
      url: {
        type: Schema.types.string,
        description:
          "The URL where users can edit the new survey before sending",
        title: "Design survey URL",
      },
    },
    required: ["id", "title", "url"],
  },
});
