/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import UpdateIssue from "./update_issue.ts";

Deno.test("UpdateIssue can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UpdateIssue_slack_function",
    title: "Test UpdateIssue",
    description: "This is a generated test to test UpdateIssue",
  });
  testWorkflow.addStep(UpdateIssue, {
    repository: "test",
    issue_number: "test",
    github_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A050QFW22F5#/functions/update_issue");
  assertEquals(actual.inputs, {
    repository: "test",
    issue_number: "test",
    github_access_token: "test",
  });
});

Deno.test("All outputs of Slack function UpdateIssue should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UpdateIssue_slack_function",
    title: "Test UpdateIssue",
    description: "This is a generated test to test UpdateIssue",
  });
  const step = testWorkflow.addStep(UpdateIssue, {
    repository: "test",
    issue_number: "test",
    github_access_token: "test",
  });
  assertExists(step.outputs.issue_number);
  assertExists(step.outputs.issue_url);
  assertExists(step.outputs.title);
  assertExists(step.outputs.description);
});
