/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateFile from "./create_file.ts";

Deno.test("CreateFile can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateFile_slack_function",
    title: "Test CreateFile",
    description: "This is a generated test to test CreateFile",
  });
  testWorkflow.addStep(CreateFile, {
    onedrive_access_token: "test",
    file_name: "test",
    file_type: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05QGK4DF8A#/functions/create_file");
  assertEquals(actual.inputs, {
    onedrive_access_token: "test",
    file_name: "test",
    file_type: "test",
  });
});

Deno.test("All outputs of Slack function CreateFile should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateFile_slack_function",
    title: "Test CreateFile",
    description: "This is a generated test to test CreateFile",
  });
  const step = testWorkflow.addStep(CreateFile, {
    onedrive_access_token: "test",
    file_name: "test",
    file_type: "test",
  });
  assertExists(step.outputs.file_url);
  assertExists(step.outputs.file_name);
});
