/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05U2T0F8PP#/functions/archive_board",
  title: "Archive a board",
  input_parameters: {
    properties: {
      monday_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Monday Access Token",
      },
      board_id: {
        type: Schema.types.string,
        description: "Select a board",
        title: "Board",
      },
    },
    required: ["monday_access_token", "board_id"],
  },
  output_parameters: {
    properties: {
      board_id: { type: Schema.types.string, title: "Board ID" },
      board_name: { type: Schema.types.string, title: "Board name" },
    },
    required: [],
  },
});
