/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05U2T0F8PP#/functions/create_board",
  title: "Create a board",
  input_parameters: {
    properties: {
      monday_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Monday Access Token",
      },
      board_name: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Board name",
      },
      board_kind: {
        type: Schema.types.string,
        title: "Board type",
        enum: ["public", "private", "share"],
      },
      description: {
        type: Schema.types.string,
        description: "Enter description...",
        title: "Description",
      },
    },
    required: ["monday_access_token", "board_name", "board_kind"],
  },
  output_parameters: {
    properties: {
      board_id: { type: Schema.types.string, title: "Board ID" },
      board_name: { type: Schema.types.string, title: "Board name" },
      board_url: { type: Schema.types.string, title: "Board URL" },
    },
    required: [],
  },
});
