/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05U2T0F8PP#/functions/create_group",
  title: "Create a group",
  input_parameters: {
    properties: {
      monday_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Monday Access Token",
      },
      board_id: {
        type: Schema.types.string,
        description: "Select a board",
        title: "Board",
      },
      group_name: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Group name",
      },
    },
    required: ["monday_access_token", "board_id", "group_name"],
  },
  output_parameters: {
    properties: {
      group_id: { type: Schema.types.string, title: "Group ID" },
      group_name: { type: Schema.types.string, title: "Group name" },
    },
    required: [],
  },
});
