/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05U2T0F8PP#/functions/create_item",
  title: "Create an item",
  input_parameters: {
    properties: {
      monday_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Monday Access Token",
      },
      board_id: {
        type: Schema.types.string,
        description: "Select a board",
        title: "Board",
      },
      group_id: {
        type: Schema.types.string,
        description: "Select a group",
        title: "Group",
      },
      item_name: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Item name",
      },
    },
    required: ["monday_access_token", "board_id", "item_name"],
  },
  output_parameters: {
    properties: {
      item_id: { type: Schema.types.string, title: "Item ID" },
      item_name: { type: Schema.types.string, title: "Item name" },
    },
    required: [],
  },
});
