/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineFunction } from "../../deps.ts";
import { Schema } from "../../deps.ts";

export default DefineFunction({
  callback_id: "A04MG80N5CY#/functions/add_spreadsheet_row",
  source_file: "",
  title: "Add a spreadsheet row - Beta",
  description: "This step adds a new row to a Google sheet",
  input_parameters: {
    properties: {
      spreadsheet_id: {
        type: Schema.types.string,
        description: "Select a spreadsheet",
        title: "Spreadsheet",
      },
      sheet_title: {
        type: Schema.types.string,
        description: "Sheet",
        title: "Sheet",
      },
      columns: {
        type: Schema.types.array,
        description: "Columns",
        title: "Columns",
        items: { type: Schema.types.string },
      },
      google_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Google Credential to use",
        title: "Google Access Token",
      },
    },
    required: [
      "spreadsheet_id",
      "sheet_title",
      "columns",
      "google_access_token",
    ],
  },
  output_parameters: {
    properties: {
      spreadsheet_id: {
        type: Schema.types.string,
        description: "Spreadsheet Id",
        title: "Spreadsheet Id",
      },
    },
    required: ["spreadsheet_id"],
  },
});
