/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals } from "../../dev_deps.ts";
import { DefineWorkflow } from "../../dev_deps.ts";
import { ManifestFunctionSchema } from "../../dev_deps.ts";
import { Schema } from "../../deps.ts";
import DeleteSpreadsheetRow from "./delete_spreadsheet_row.ts";

Deno.test("DeleteSpreadsheetRow generates valid FunctionManifest", () => {
  assertEquals(
    DeleteSpreadsheetRow.definition.callback_id,
    "slack#/functions/delete_spreadsheet_row",
  );
  const expected: ManifestFunctionSchema = {
    source_file: "",
    title: "Delete a spreadsheet row - Beta",
    description: "This function deletes a row from a spreadsheet",
    input_parameters: {
      properties: {
        spreadsheet_id: {
          type: Schema.types.string,
          description: "Select a spreadsheet",
          title: "Spreadsheet",
        },
        sheet: {
          type: Schema.types.string,
          description: "Sheet",
          title: "Sheet",
        },
        sheet_title: {
          type: Schema.types.string,
          description: "Sheet",
          title: "Sheet",
        },
        column_name: {
          type: Schema.types.string,
          description: "Sheet",
          title: "Column Name",
        },
        cell_value: {
          type: Schema.types.string,
          description: "Cell Search Value",
          title: "Cell Search Value",
        },
        google_access_token: {
          type: Schema.slack.types.oauth2,
          description: "Google Credential to use",
          title: "Google Access Token",
        },
      },
      required: [
        "spreadsheet_id",
        "sheet",
        "sheet_title",
        "column_name",
        "cell_value",
        "google_access_token",
      ],
    },
    output_parameters: { properties: {}, required: [] },
  };
  const actual = DeleteSpreadsheetRow.export();

  assertEquals(actual, expected);
});

Deno.test("DeleteSpreadsheetRow can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_DeleteSpreadsheetRow_slack_function",
    title: "Test DeleteSpreadsheetRow",
    description: "This is a generated test to test DeleteSpreadsheetRow",
  });
  testWorkflow.addStep(DeleteSpreadsheetRow, {
    spreadsheet_id: "test",
    sheet: "test",
    sheet_title: "test",
    column_name: "test",
    cell_value: "test",
    google_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "slack#/functions/delete_spreadsheet_row");
  assertEquals(actual.inputs, {
    spreadsheet_id: "test",
    sheet: "test",
    sheet_title: "test",
    column_name: "test",
    cell_value: "test",
    google_access_token: "test",
  });
});
