/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import AddSpreadsheetRow from "./functions/add_spreadsheet_row.ts";
import DeleteSpreadsheetRow from "./functions/delete_spreadsheet_row.ts";
import SelectSpreadsheetRow from "./functions/select_spreadsheet_row.ts";
import UpdateSpreadsheetRow from "./functions/update_spreadsheet_row.ts";

const GoogleSheets = {
  functions: {
    AddSpreadsheetRow,
    DeleteSpreadsheetRow,
    SelectSpreadsheetRow,
    UpdateSpreadsheetRow,
  },
} as const;

export default GoogleSheets;
