/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateMeeting from "./create_meeting.ts";

Deno.test("CreateMeeting can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateMeeting_slack_function",
    title: "Test CreateMeeting",
    description: "This is a generated test to test CreateMeeting",
  });
  testWorkflow.addStep(CreateMeeting, {
    teams_access_token: "test",
    subject: "test",
    start_time: "test",
    end_time: "test",
    timezone: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05Q9UPHBDL#/functions/create_meeting");
  assertEquals(actual.inputs, {
    teams_access_token: "test",
    subject: "test",
    start_time: "test",
    end_time: "test",
    timezone: "test",
  });
});

Deno.test("All outputs of Slack function CreateMeeting should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateMeeting_slack_function",
    title: "Test CreateMeeting",
    description: "This is a generated test to test CreateMeeting",
  });
  const step = testWorkflow.addStep(CreateMeeting, {
    teams_access_token: "test",
    subject: "test",
    start_time: "test",
    end_time: "test",
    timezone: "test",
  });
  assertExists(step.outputs.meeting_url);
  assertExists(step.outputs.meeting_id);
});
