/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05Q9UPHBDL#/functions/create_meeting",
  title: "Create a meeting",
  description: "Creates an online meeting in Microsoft Teams",
  input_parameters: {
    properties: {
      teams_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Microsoft credential to use",
        title: "Microsoft access token",
      },
      subject: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Subject",
      },
      start_time: { type: Schema.slack.types.timestamp, title: "Start time" },
      end_time: { type: Schema.slack.types.timestamp, title: "End time" },
      timezone: {
        type: Schema.types.string,
        description: "Select a timezone",
        title: "Timezone",
      },
    },
    required: [
      "teams_access_token",
      "subject",
      "start_time",
      "end_time",
      "timezone",
    ],
  },
  output_parameters: {
    properties: {
      meeting_url: { type: Schema.types.string, title: "Meeting URL" },
      meeting_id: {
        type: Schema.types.string,
        description: "Meeting ID",
        title: "Meeting ID",
      },
    },
    required: [],
  },
});
