/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import DeleteRow from "./delete_row.ts";

Deno.test("DeleteRow can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_DeleteRow_slack_function",
    title: "Test DeleteRow",
    description: "This is a generated test to test DeleteRow",
  });
  testWorkflow.addStep(DeleteRow, {
    sheet: "test",
    select_row: "test",
    smartsheet_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05SEF35LQY#/functions/delete_row");
  assertEquals(actual.inputs, {
    sheet: "test",
    select_row: "test",
    smartsheet_access_token: "test",
  });
});

Deno.test("All outputs of Slack function DeleteRow should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_DeleteRow_slack_function",
    title: "Test DeleteRow",
    description: "This is a generated test to test DeleteRow",
  });
  const step = testWorkflow.addStep(DeleteRow, {
    sheet: "test",
    select_row: "test",
    smartsheet_access_token: "test",
  });
  assertExists(step.outputs.smartsheet_url);
  assertExists(step.outputs.sheet_id);
});
