/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05SEF35LQY#/functions/select_row",
  title: "Select a Smartsheet row",
  input_parameters: {
    properties: {
      sheet: {
        type: Schema.types.object,
        description: "Select a Smartsheet",
        title: "Smartsheet",
      },
      select_row: {
        type: Schema.types.string,
        description: "Search a row with cell value",
        title: "Select a row",
      },
      smartsheet_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Which account should we use to fetch Smartsheets?",
        title: "Smartsheet Access Token",
      },
    },
    required: ["sheet", "select_row", "smartsheet_access_token"],
  },
  output_parameters: {
    properties: {
      smartsheet_url: {
        type: Schema.types.string,
        description: "Smartsheet URL",
        title: "Smartsheet URL",
      },
      sheet_id: {
        type: Schema.types.string,
        description: "Smartsheet ID",
        title: "Smartsheet ID",
      },
      row: {
        type: Schema.types.object,
        description: "Row",
        title: "Row",
        properties: {
          id: { type: Schema.types.integer, title: "Row ID" },
          rowNumber: { type: Schema.types.integer, title: "Row number" },
        },
        additionalProperties: true,
        required: [],
      },
      column_values: { type: Schema.types.object, title: "Column values" },
    },
    required: ["smartsheet_url", "sheet_id", "row", "column_values"],
  },
});
