/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A050C90PUF5#/functions/update_event",
  title: "Update a calendar event",
  input_parameters: {
    properties: {
      google_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Google Credential to use",
        title: "Google Access Token",
      },
      calendar_id: {
        type: Schema.types.string,
        description: "Select a Google Calendar",
        title: "Calendar",
      },
      event_id: {
        type: Schema.types.string,
        description: "Select an event from the chosen calendar",
        title: "Event",
      },
      start_time: {
        type: Schema.slack.types.timestamp,
        description: "Start time for event",
        title: "Start time",
      },
      end_time: {
        type: Schema.slack.types.timestamp,
        description: "End time for event",
        title: "End time",
      },
      summary: {
        type: Schema.types.string,
        description: "Event title",
        title: "Event title",
      },
      location: {
        type: Schema.types.string,
        description: "Location of event",
        title: "Location",
      },
      description: {
        type: Schema.types.string,
        description: "Description of event",
        title: "Description",
      },
    },
    required: ["calendar_id", "event_id", "start_time", "end_time"],
  },
  output_parameters: {
    properties: {
      event_summary: {
        type: Schema.types.string,
        description: "Title of the event",
        title: "Event title",
      },
      event_url: {
        type: Schema.types.string,
        description: "URL of the event",
        title: "Event URL",
      },
    },
    required: [],
  },
});
