/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CopyDocument from "./copy_document.ts";

Deno.test("CopyDocument can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CopyDocument_slack_function",
    title: "Test CopyDocument",
    description: "This is a generated test to test CopyDocument",
  });
  testWorkflow.addStep(CopyDocument, {
    document_type: "test",
    from_path: "test",
    name: "test",
    dropbox_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05U3EFESFR#/functions/copy_document");
  assertEquals(actual.inputs, {
    document_type: "test",
    from_path: "test",
    name: "test",
    dropbox_access_token: "test",
  });
});

Deno.test("All outputs of Slack function CopyDocument should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CopyDocument_slack_function",
    title: "Test CopyDocument",
    description: "This is a generated test to test CopyDocument",
  });
  const step = testWorkflow.addStep(CopyDocument, {
    document_type: "test",
    from_path: "test",
    name: "test",
    dropbox_access_token: "test",
  });
  assertExists(step.outputs.id);
  assertExists(step.outputs.name);
  assertExists(step.outputs.path_display);
});
