/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import DeleteDocument from "./delete_document.ts";

Deno.test("DeleteDocument can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_DeleteDocument_slack_function",
    title: "Test DeleteDocument",
    description: "This is a generated test to test DeleteDocument",
  });
  testWorkflow.addStep(DeleteDocument, {
    document_type: "test",
    path: "test",
    dropbox_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05U3EFESFR#/functions/delete_document");
  assertEquals(actual.inputs, {
    document_type: "test",
    path: "test",
    dropbox_access_token: "test",
  });
});

Deno.test("All outputs of Slack function DeleteDocument should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_DeleteDocument_slack_function",
    title: "Test DeleteDocument",
    description: "This is a generated test to test DeleteDocument",
  });
  const step = testWorkflow.addStep(DeleteDocument, {
    document_type: "test",
    path: "test",
    dropbox_access_token: "test",
  });
  assertExists(step.outputs.id);
  assertExists(step.outputs.name);
  assertExists(step.outputs.path_display);
});
