/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import AddANote from "./add_a_note.ts";

Deno.test("AddANote can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_AddANote_slack_function",
    title: "Test AddANote",
    description: "This is a generated test to test AddANote",
  });
  testWorkflow.addStep(AddANote, {
    incident_id: "test",
    content: "test",
    pagerduty_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A04RSGH23L7#/functions/add_a_note");
  assertEquals(actual.inputs, {
    incident_id: "test",
    content: "test",
    pagerduty_access_token: "test",
  });
});

Deno.test("All outputs of Slack function AddANote should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_AddANote_slack_function",
    title: "Test AddANote",
    description: "This is a generated test to test AddANote",
  });
  const step = testWorkflow.addStep(AddANote, {
    incident_id: "test",
    content: "test",
    pagerduty_access_token: "test",
  });
  assertExists(step.outputs.content);
  assertExists(step.outputs.created_at);
});
