/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A04RSGH23L7#/functions/create_incident",
  title: "Trigger an incident",
  description: "Trigger a PagerDuty incident",
  input_parameters: {
    properties: {
      title: {
        type: Schema.types.string,
        description: "Enter incident title...",
        title: "Incident title",
      },
      details: {
        type: Schema.types.string,
        description: "Enter incident details...",
        title: "Incident details",
      },
      pagerduty_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Pagerduty access token",
        title: "PagerDuty access token",
      },
      service_id: {
        type: Schema.types.string,
        description: "PagerDuty Service",
        title: "Service",
      },
      escalation_policy: {
        type: Schema.types.string,
        description: "PagerDuty Escalation policy",
        title: "Escalation policy",
      },
    },
    required: [
      "title",
      "details",
      "pagerduty_access_token",
      "service_id",
      "escalation_policy",
    ],
  },
  output_parameters: {
    properties: {
      incident_id: {
        type: Schema.types.string,
        description: "Incident ID",
        title: "Incident ID",
      },
      incident_url: {
        type: Schema.types.string,
        description: "Incident URL",
        title: "Incident URL",
      },
      incident_title: {
        type: Schema.types.string,
        description: "Incident title",
        title: "Incident title",
      },
      incident_details: {
        type: Schema.types.string,
        description: "Incident details",
        title: "Incident details",
      },
      escalation_policy: {
        type: Schema.types.object,
        description: "Escalation Policy",
        title: "Escalation policy",
        properties: {
          id: { type: Schema.types.string, title: "Escalation policy ID" },
          summary: {
            type: Schema.types.string,
            title: "Escalation policy summary",
          },
          html_url: {
            type: Schema.types.string,
            title: "Escalation policy URL",
          },
        },
        additionalProperties: true,
        required: [],
      },
      service: {
        type: Schema.types.object,
        description: "Service",
        title: "Service",
        properties: {
          id: { type: Schema.types.string, title: "Service ID" },
          summary: { type: Schema.types.string, title: "Service summary" },
          html_url: { type: Schema.types.string, title: "Service URL" },
        },
        additionalProperties: true,
        required: [],
      },
      team: {
        type: Schema.types.object,
        description: "Team",
        title: "Team",
        properties: {
          id: { type: Schema.types.string, title: "Team ID" },
          summary: { type: Schema.types.string, title: "Team summary" },
          html_url: { type: Schema.types.string, title: "Team URL" },
        },
        additionalProperties: true,
        required: [],
      },
    },
    required: [],
  },
});
