/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A04RSGH23L7#/functions/send_status_update",
  title: "Create a status update",
  description: "You'll choose an incident to get the update",
  input_parameters: {
    properties: {
      incident_id: {
        type: Schema.types.string,
        description: "Enter incident name",
        title: "Incident",
      },
      message: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Status update",
      },
      subject: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Status update email subject",
      },
      html_message: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Status update email",
      },
      pagerduty_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Pagerduty access token",
        title: "PagerDuty access token",
      },
    },
    required: ["incident_id", "message", "pagerduty_access_token"],
  },
  output_parameters: {
    properties: {
      id: {
        type: Schema.types.string,
        description: "Status update ID",
        title: "Status update ID",
      },
      sender: {
        type: Schema.types.object,
        title: "Created by",
        properties: {
          id: { type: Schema.types.string, title: "ID" },
          type: { type: Schema.types.string, title: "Type" },
          summary: { type: Schema.types.string, title: "Name" },
          html_url: { type: Schema.types.string, title: "URL" },
        },
        additionalProperties: true,
        required: [],
      },
      message: { type: Schema.types.string, title: "Status update" },
      subject: {
        type: Schema.types.string,
        title: "Status update email subject",
      },
      html_message: { type: Schema.types.string, title: "Status update email" },
      created_at: { type: Schema.slack.types.timestamp, title: "Created at" },
    },
    required: ["id", "sender", "message", "created_at"],
  },
});
