/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A04RSGH23L7#/functions/update_incident",
  title: "Update an incident",
  description: "Update a PagerDuty incident",
  input_parameters: {
    properties: {
      incident_id: {
        type: Schema.types.string,
        description: "Enter incident name",
        title: "Incident",
      },
      pagerduty_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Pagerduty access token",
        title: "PagerDuty access token",
      },
      incident_title: {
        type: Schema.types.string,
        description: "Enter incident title",
        title: "Incident title",
      },
      priority_id: { type: Schema.types.string, title: "Priority" },
      escalation_policy: {
        type: Schema.types.string,
        description: "PagerDuty Escalation policy",
        title: "Escalation policy",
      },
      urgency: {
        type: Schema.types.string,
        title: "Urgency",
        enum: ["high", "low"],
      },
      status: {
        type: Schema.types.string,
        title: "Status",
        enum: ["acknowledged", "resolved"],
      },
      resolution_note: {
        type: Schema.types.string,
        description: "Enter a resolution note",
        title: "Resolution note",
      },
    },
    required: ["incident_id", "pagerduty_access_token"],
  },
  output_parameters: {
    properties: {
      incident_id: {
        type: Schema.types.string,
        description: "Incident ID",
        title: "Incident ID",
      },
      incident_url: {
        type: Schema.types.string,
        description: "Incident URL",
        title: "Incident URL",
      },
      incident_title: {
        type: Schema.types.string,
        description: "Incident title",
        title: "Incident title",
      },
      incident_details: {
        type: Schema.types.string,
        description: "Incident details",
        title: "Incident details",
      },
      escalation_policy: {
        type: Schema.types.object,
        description: "Escalation Policy",
        title: "Escalation policy",
        properties: {
          id: { type: Schema.types.string, title: "Escalation policy ID" },
          summary: {
            type: Schema.types.string,
            title: "Escalation policy summary",
          },
          html_url: {
            type: Schema.types.string,
            title: "Escalation policy URL",
          },
        },
        additionalProperties: true,
        required: [],
      },
      service: {
        type: Schema.types.object,
        description: "Service",
        title: "Service",
        properties: {
          id: { type: Schema.types.string, title: "Service ID" },
          summary: { type: Schema.types.string, title: "Service summary" },
          html_url: { type: Schema.types.string, title: "Service URL" },
        },
        additionalProperties: true,
        required: [],
      },
      team: {
        type: Schema.types.object,
        description: "Team",
        title: "Team",
        properties: {
          id: { type: Schema.types.string, title: "Team ID" },
          summary: { type: Schema.types.string, title: "Team summary" },
          html_url: { type: Schema.types.string, title: "Team URL" },
        },
        additionalProperties: true,
        required: [],
      },
    },
    required: [],
  },
});
