/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A04T99UKKQE#/functions/create_record",
  title: "Create a record",
  description: "Create a Salesforce record",
  input_parameters: {
    properties: {
      salesforce_object_name: {
        type: Schema.types.string,
        description: "Select an option...",
        title: "Salesforce object",
      },
      metadata: {
        type: Schema.types.object,
        description: "Select an field",
        title: "Name",
      },
      salesforce_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Salesforce Access Token",
      },
    },
    required: ["salesforce_object_name", "salesforce_access_token"],
  },
  output_parameters: {
    properties: {
      success: { type: Schema.types.boolean, title: "Response" },
      record_id: { type: Schema.types.string, title: "Record ID" },
      record_url: { type: Schema.types.string, title: "Record URL" },
    },
    required: [],
  },
});
