/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import DeleteRecord from "./delete_record.ts";

Deno.test("DeleteRecord can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_DeleteRecord_slack_function",
    title: "Test DeleteRecord",
    description: "This is a generated test to test DeleteRecord",
  });
  testWorkflow.addStep(DeleteRecord, {
    salesforce_object_name: "test",
    record_id: "test",
    salesforce_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A04T99UKKQE#/functions/delete_record");
  assertEquals(actual.inputs, {
    salesforce_object_name: "test",
    record_id: "test",
    salesforce_access_token: "test",
  });
});

Deno.test("All outputs of Slack function DeleteRecord should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_DeleteRecord_slack_function",
    title: "Test DeleteRecord",
    description: "This is a generated test to test DeleteRecord",
  });
  const step = testWorkflow.addStep(DeleteRecord, {
    salesforce_object_name: "test",
    record_id: "test",
    salesforce_access_token: "test",
  });
  assertExists(step.outputs.code);
  assertExists(step.outputs.record_id);
});
