/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import RunFlow from "./run_flow.ts";

const Salesforce = { RunFlow } as const;

export default Salesforce;
