/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A04T99UKKQE#/functions/read_record",
  title: "Read a record",
  description: "Read a Salesforce record",
  input_parameters: {
    properties: {
      salesforce_object_name: {
        type: Schema.types.string,
        description: "Salesforce Object",
        title: "Salesforce object",
      },
      record_id: {
        type: Schema.slack.types.salesforce_record_id,
        title: "Record",
      },
      salesforce_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Salesforce Access Token",
      },
    },
    required: [
      "salesforce_object_name",
      "record_id",
      "salesforce_access_token",
    ],
  },
  output_parameters: {
    properties: {
      record: { type: Schema.types.object, title: "Record fields" },
      salesforce_object_type: {
        type: Schema.types.string,
        title: "Salesforce Object Type",
      },
      record_url: { type: Schema.types.string, title: "Record URL" },
    },
    required: [],
  },
});
