/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import ReadRecord from "./read_record.ts";

Deno.test("ReadRecord can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_ReadRecord_slack_function",
    title: "Test ReadRecord",
    description: "This is a generated test to test ReadRecord",
  });
  testWorkflow.addStep(ReadRecord, {
    salesforce_object_name: "test",
    record_id: "test",
    salesforce_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A04T99UKKQE#/functions/read_record");
  assertEquals(actual.inputs, {
    salesforce_object_name: "test",
    record_id: "test",
    salesforce_access_token: "test",
  });
});

Deno.test("All outputs of Slack function ReadRecord should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_ReadRecord_slack_function",
    title: "Test ReadRecord",
    description: "This is a generated test to test ReadRecord",
  });
  const step = testWorkflow.addStep(ReadRecord, {
    salesforce_object_name: "test",
    record_id: "test",
    salesforce_access_token: "test",
  });
  assertExists(step.outputs.record);
  assertExists(step.outputs.salesforce_object_type);
  assertExists(step.outputs.record_url);
});
