/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateMeeting from "./functions/create_meeting.ts";
import UpdateMeeting from "./functions/update_meeting.ts";

const MicrosoftTeams = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/microsoft.teams/create_meeting CreateMeeting} documentation.
     */
    CreateMeeting,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/microsoft.teams/update_meeting UpdateMeeting} documentation.
     */
    UpdateMeeting,
  },
} as const;

export default MicrosoftTeams;
