/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateIncident from "./functions/create_incident.ts";
import CreateTask from "./functions/create_task.ts";
import UpdateIncident from "./functions/update_incident.ts";
import UpdateTask from "./functions/update_task.ts";

const Firehydrant = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/firehydrant/create_incident CreateIncident} documentation.
     */
    CreateIncident,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/firehydrant/create_task CreateTask} documentation.
     */
    CreateTask,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/firehydrant/update_incident UpdateIncident} documentation.
     */
    UpdateIncident,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/firehydrant/update_task UpdateTask} documentation.
     */
    UpdateTask,
  },
} as const;

export default Firehydrant;
