/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreatePage from "./functions/create_page.ts";
import UpdatePage from "./functions/update_page.ts";

const MicrosoftOnenote = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/microsoft.onenote/create_page CreatePage} documentation.
     */
    CreatePage,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/microsoft.onenote/update_page UpdatePage} documentation.
     */
    UpdatePage,
  },
} as const;

export default MicrosoftOnenote;
