/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import AddTaskToSection from "./add_task_to_section.ts";

Deno.test("AddTaskToSection can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_AddTaskToSection_slack_function",
    title: "Test AddTaskToSection",
    description: "This is a generated test to test AddTaskToSection",
  });
  testWorkflow.addStep(AddTaskToSection, {
    asana_access_token: "test",
    workspace_gid: "test",
    project: "test",
    section_gid: "test",
    task_gid: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(
    actual.function_id,
    "A05KUFPF86S#/functions/add_task_to_section",
  );
  assertEquals(actual.inputs, {
    asana_access_token: "test",
    workspace_gid: "test",
    project: "test",
    section_gid: "test",
    task_gid: "test",
  });
});

Deno.test("All outputs of Slack function AddTaskToSection should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_AddTaskToSection_slack_function",
    title: "Test AddTaskToSection",
    description: "This is a generated test to test AddTaskToSection",
  });
  const step = testWorkflow.addStep(AddTaskToSection, {
    asana_access_token: "test",
    workspace_gid: "test",
    project: "test",
    section_gid: "test",
    task_gid: "test",
  });
  assertExists(step.outputs.response_code);
});
