/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05KUFPF86S#/functions/create_task",
  title: "Create a task",
  input_parameters: {
    properties: {
      workspace_gid: { type: Schema.types.string, title: "Workspace" },
      project: { type: Schema.types.string, title: "Project" },
      assignee_section: { type: Schema.types.string, title: "Section" },
      assignee: {
        type: Schema.slack.types.user_id,
        description: "Select a user",
        title: "Assignee",
      },
      name: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Task name",
      },
      start_at: { type: Schema.slack.types.timestamp, title: "Start at" },
      due_at: { type: Schema.slack.types.timestamp, title: "Due at" },
      description: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Description",
      },
      tags: {
        type: Schema.types.array,
        title: "Tags",
        items: { type: Schema.types.string },
      },
      collaborators: {
        type: Schema.types.array,
        title: "Collaborators",
        items: { type: Schema.slack.types.user_id },
      },
      asana_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Asana credential to use",
        title: "Asana Access Token",
      },
    },
    required: [
      "workspace_gid",
      "project",
      "assignee",
      "name",
      "asana_access_token",
    ],
  },
  output_parameters: {
    properties: {
      assignee: {
        type: Schema.types.string,
        description: "The name of the user assigned to the task",
        title: "Assignee of task",
      },
      task_name: {
        type: Schema.types.string,
        description: "The name of the task",
        title: "Task name",
      },
      start_at: {
        type: Schema.types.string,
        description: "The datetime the task is to be started on",
        title: "Start at",
      },
      due_at: {
        type: Schema.types.string,
        description: "The datetime the task is due at",
        title: "Due at",
      },
      description: {
        type: Schema.types.string,
        description: "The description for the task",
        title: "Description",
      },
      created_at: {
        type: Schema.types.string,
        description: "The datetime the task was created at",
        title: "Created at",
      },
      permalink_url: {
        type: Schema.types.string,
        description: "Link for the created task",
        title: "Link to task",
      },
      collaborator_emails: {
        type: Schema.types.array,
        description: "Emails of the Collaborators with comma separated",
        title: "Collaborator emails",
        items: { type: Schema.types.string },
      },
    },
    required: ["task_name", "permalink_url"],
  },
});
