/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateTask from "./create_task.ts";

Deno.test("CreateTask can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateTask_slack_function",
    title: "Test CreateTask",
    description: "This is a generated test to test CreateTask",
  });
  testWorkflow.addStep(CreateTask, {
    workspace_gid: "test",
    project: "test",
    assignee: "test",
    name: "test",
    asana_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05KUFPF86S#/functions/create_task");
  assertEquals(actual.inputs, {
    workspace_gid: "test",
    project: "test",
    assignee: "test",
    name: "test",
    asana_access_token: "test",
  });
});

Deno.test("All outputs of Slack function CreateTask should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateTask_slack_function",
    title: "Test CreateTask",
    description: "This is a generated test to test CreateTask",
  });
  const step = testWorkflow.addStep(CreateTask, {
    workspace_gid: "test",
    project: "test",
    assignee: "test",
    name: "test",
    asana_access_token: "test",
  });
  assertExists(step.outputs.assignee);
  assertExists(step.outputs.task_name);
  assertExists(step.outputs.start_at);
  assertExists(step.outputs.due_at);
  assertExists(step.outputs.description);
  assertExists(step.outputs.created_at);
  assertExists(step.outputs.permalink_url);
  assertExists(step.outputs.collaborator_emails);
});
