/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import SendSignatureRequestWithTemplate from "./functions/send_signature_request_with_template.ts";

const DropboxSign = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/dropbox.sign/send_signature_request_with_template SendSignatureRequestWithTemplate} documentation.
     */
    SendSignatureRequestWithTemplate,
  },
} as const;

export default DropboxSign;
