/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A07AYPT9X4P#/functions/create_incident",
  title: "Create an incident",
  input_parameters: {
    properties: {
      short_description: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Short description",
      },
      caller_id: {
        type: Schema.types.string,
        description: "Select caller ID",
        title: "Caller ID",
      },
      metadata: {
        type: Schema.types.object,
        description: "Select an field",
        title: "Name",
      },
      servicenow_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Servicenow Credential to use",
        title: "Servicenow Access Token",
      },
    },
    required: ["short_description", "caller_id", "servicenow_access_token"],
  },
  output_parameters: {
    properties: {
      incident_id: {
        type: Schema.types.string,
        description: "Incident ID",
        title: "Incident ID",
      },
      incident_url: {
        type: Schema.types.string,
        description: "Incident URL",
        title: "Incident URL",
      },
      incident_number: {
        type: Schema.types.string,
        description: "Incident number",
        title: "Incident number",
      },
      incident: { type: Schema.types.object, title: "Incident" },
      timestamp_started: {
        type: Schema.slack.types.timestamp,
        description: "Time when step started",
        title: "Time when step started",
      },
      timestamp_completed: {
        type: Schema.slack.types.timestamp,
        description: "Time when step completed",
        title: "Time when step completed",
      },
    },
    required: [
      "incident_id",
      "incident_url",
      "incident_number",
      "incident",
      "timestamp_started",
      "timestamp_completed",
    ],
  },
});
