/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A07AYPT9X4P#/functions/get_incident",
  title: "Get an incident",
  input_parameters: {
    properties: {
      incident_number: {
        type: Schema.types.string,
        description: "Search incident",
        title: "Incident number",
      },
      servicenow_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Servicenow Credential to use",
        title: "Servicenow Access Token",
      },
    },
    required: ["incident_number", "servicenow_access_token"],
  },
  output_parameters: {
    properties: {
      incident_sys_id: {
        type: Schema.types.string,
        description: "Incident sys_id",
        title: "Incident sys_id",
      },
      incident_short_description: {
        type: Schema.types.string,
        description: "Incident short description",
        title: "Incident short description",
      },
      incident_state: {
        type: Schema.types.string,
        description: "Incident state",
        title: "Incident state",
      },
      incident_number: {
        type: Schema.types.string,
        description: "Incident number",
        title: "Incident number",
      },
      incident_priority: {
        type: Schema.types.string,
        description: "Incident priority",
        title: "Incident priority",
      },
      incident_url: {
        type: Schema.types.string,
        description: "Incident url",
        title: "Incident url",
      },
      timestamp_started: {
        type: Schema.slack.types.timestamp,
        description: "Time when step started",
        title: "Time when step started",
      },
      timestamp_completed: {
        type: Schema.slack.types.timestamp,
        description: "Time when step completed",
        title: "Time when step completed",
      },
    },
    required: [
      "incident_sys_id",
      "incident_short_description",
      "incident_state",
      "incident_number",
      "incident_priority",
      "incident_url",
      "timestamp_started",
      "timestamp_completed",
    ],
  },
});
