/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import GetChatGptResponse from "./get_chatGPT_response.ts";

Deno.test("GetChatGptResponse can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_GetChatGptResponse_slack_function",
    title: "Test GetChatGptResponse",
    description: "This is a generated test to test GetChatGptResponse",
  });
  testWorkflow.addStep(GetChatGptResponse, { prompt: "test" });
  const actual = testWorkflow.steps[0].export();

  assertEquals(
    actual.function_id,
    "A05AF8B1SSU#/functions/get_chatGPT_response",
  );
  assertEquals(actual.inputs, { prompt: "test" });
});

Deno.test("All outputs of Slack function GetChatGptResponse should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_GetChatGptResponse_slack_function",
    title: "Test GetChatGptResponse",
    description: "This is a generated test to test GetChatGptResponse",
  });
  const step = testWorkflow.addStep(GetChatGptResponse, { prompt: "test" });
  assertExists(step.outputs.chatGPT_response);
});
