/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateIssue from "./functions/create_issue.ts";

const Gitlab = { functions: { CreateIssue } } as const;

export default Gitlab;
