/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateMeeting from "./create_meeting.ts";

const Webex = { CreateMeeting } as const;

export default Webex;
