/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import DeleteWorksheetRow from "./delete_worksheet_row.ts";

Deno.test("DeleteWorksheetRow can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_DeleteWorksheetRow_slack_function",
    title: "Test DeleteWorksheetRow",
    description: "This is a generated test to test DeleteWorksheetRow",
  });
  testWorkflow.addStep(DeleteWorksheetRow, {
    workbook: "test",
    worksheet_name: "test",
    column_name: "test",
    cell_value: "test",
    excel_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(
    actual.function_id,
    "A05UVANN1S4#/functions/delete_worksheet_row",
  );
  assertEquals(actual.inputs, {
    workbook: "test",
    worksheet_name: "test",
    column_name: "test",
    cell_value: "test",
    excel_access_token: "test",
  });
});

Deno.test("All outputs of Slack function DeleteWorksheetRow should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_DeleteWorksheetRow_slack_function",
    title: "Test DeleteWorksheetRow",
    description: "This is a generated test to test DeleteWorksheetRow",
  });
  const step = testWorkflow.addStep(DeleteWorksheetRow, {
    workbook: "test",
    worksheet_name: "test",
    column_name: "test",
    cell_value: "test",
    excel_access_token: "test",
  });
  assertExists(step.outputs.worksheet_url);
  assertExists(step.outputs.worksheet_name);
  assertExists(step.outputs.row_id);
});
