/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05UVANN1S4#/functions/select_worksheet_row",
  title: "Select a worksheet row",
  description: "Select the first matched row in a worksheet",
  input_parameters: {
    properties: {
      workbook: {
        type: Schema.types.object,
        description: "Select a workbook",
        title: "Workbook",
      },
      worksheet_name: {
        type: Schema.types.string,
        description: "Select a worksheet",
        title: "Worksheet",
      },
      column_name: {
        type: Schema.types.string,
        description: "Select a column",
        title: "Choose a column to search",
      },
      cell_value: {
        type: Schema.types.string,
        description: "Add a value",
        title: "Cell value to find",
      },
      excel_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Access token for Microsoft Graph API",
        title: "Microsoft excel access token",
      },
    },
    required: [
      "workbook",
      "worksheet_name",
      "column_name",
      "cell_value",
      "excel_access_token",
    ],
  },
  output_parameters: {
    properties: {
      column_values: { type: Schema.types.object, title: "Column values" },
      row_index: {
        type: Schema.types.string,
        description: "Row index",
        title: "Row index",
      },
    },
    required: ["column_values", "row_index"],
  },
});
