/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05UVANN1S4#/functions/update_worksheet_row",
  title: "Update a worksheet",
  description: "Update a row in a Microsoft workbook worksheet",
  input_parameters: {
    properties: {
      workbook: {
        type: Schema.types.object,
        description: "Select a workbook",
        title: "Workbook",
      },
      worksheet_name: {
        type: Schema.types.string,
        description: "Select a worksheet",
        title: "Worksheet",
      },
      column_name: {
        type: Schema.types.string,
        description: "Select a column",
        title: "Choose a column to search",
      },
      cell_value: {
        type: Schema.types.string,
        description: "Add a value",
        title: "Cell value to find",
      },
      excel_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Access token for Microsoft Graph API",
        title: "Microsoft excel access token",
      },
      updated_values: { type: Schema.types.object, title: "Updated Values" },
    },
    required: [
      "workbook",
      "worksheet_name",
      "column_name",
      "cell_value",
      "excel_access_token",
      "updated_values",
    ],
  },
  output_parameters: {
    properties: {
      worksheet_url: {
        type: Schema.types.string,
        description: "Worksheet URL",
        title: "Worksheet URL",
      },
      worksheet_name: {
        type: Schema.types.string,
        description: "Worksheet name",
        title: "Worksheet name",
      },
      row_id: {
        type: Schema.types.string,
        description: "Deleted row ID",
        title: "Row ID",
      },
      column_values: { type: Schema.types.object, title: "Column values" },
    },
    required: ["worksheet_url", "worksheet_name", "row_id", "column_values"],
  },
});
