/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import SendSms from "./send_sms.ts";

Deno.test("SendSms can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_SendSms_slack_function",
    title: "Test SendSms",
    description: "This is a generated test to test SendSms",
  });
  testWorkflow.addStep(SendSms, {
    from_number: "test",
    to_numbers: "test",
    text: "test",
    dialpad_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05USRAR873#/functions/send_sms");
  assertEquals(actual.inputs, {
    from_number: "test",
    to_numbers: "test",
    text: "test",
    dialpad_access_token: "test",
  });
});

Deno.test("All outputs of Slack function SendSms should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_SendSms_slack_function",
    title: "Test SendSms",
    description: "This is a generated test to test SendSms",
  });
  const step = testWorkflow.addStep(SendSms, {
    from_number: "test",
    to_numbers: "test",
    text: "test",
    dialpad_access_token: "test",
  });
  assertExists(step.outputs.message_status);
  assertExists(step.outputs.from_number);
  assertExists(step.outputs.text);
});
