/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import StartMeeting from "./functions/start_meeting.ts";

const GoogleMeet = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/google.meet/start_meeting StartMeeting} documentation.
     */
    StartMeeting,
  },
} as const;

export default GoogleMeet;
