/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateFeatureFlag from "./create_feature_flag.ts";

Deno.test("CreateFeatureFlag can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateFeatureFlag_slack_function",
    title: "Test CreateFeatureFlag",
    description: "This is a generated test to test CreateFeatureFlag",
  });
  testWorkflow.addStep(CreateFeatureFlag, {
    project_key: "test",
    name: "test",
    key: "test",
    launchdarkly_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(
    actual.function_id,
    "A05RF94AFB3#/functions/create_feature_flag",
  );
  assertEquals(actual.inputs, {
    project_key: "test",
    name: "test",
    key: "test",
    launchdarkly_access_token: "test",
  });
});

Deno.test("All outputs of Slack function CreateFeatureFlag should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateFeatureFlag_slack_function",
    title: "Test CreateFeatureFlag",
    description: "This is a generated test to test CreateFeatureFlag",
  });
  const step = testWorkflow.addStep(CreateFeatureFlag, {
    project_key: "test",
    name: "test",
    key: "test",
    launchdarkly_access_token: "test",
  });
  assertExists(step.outputs.name);
});
