/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05RF94AFB3#/functions/create_feature_flag",
  title: "Create a boolean feature flag",
  input_parameters: {
    properties: {
      project_key: {
        type: Schema.types.string,
        description: "Please select an option",
        title: "Project",
      },
      name: {
        type: Schema.types.string,
        description: "Enter a unique, human-readable name",
        title: "Name",
      },
      key: {
        type: Schema.types.string,
        description: "Enter a unique flag key",
        title: "Key",
      },
      launchdarkly_access_token: {
        type: Schema.slack.types.oauth2,
        description: "LaunchDarkly Credential to use",
        title: "LaunchDarkly access token",
      },
    },
    required: ["project_key", "name", "key", "launchdarkly_access_token"],
  },
  output_parameters: {
    properties: {
      name: {
        type: Schema.types.string,
        description: "Feature flag name",
        title: "Name",
      },
    },
    required: ["name"],
  },
});
