/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05RF94AFB3#/functions/update_team_members",
  title: "Update team members",
  description: "Add or remove member(s) from a team",
  input_parameters: {
    properties: {
      team_key: {
        type: Schema.types.string,
        description: "Please select an option",
        title: "Team",
      },
      kind: {
        type: Schema.types.string,
        description: "Please select an option",
        title: "Operation",
        enum: ["addMembers", "removeMembers"],
      },
      member_keys: {
        type: Schema.types.array,
        description: "Select one or more members",
        title: "Member(s)",
        items: { type: Schema.types.string },
      },
      comment: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Comment",
      },
      launchdarkly_access_token: {
        type: Schema.slack.types.oauth2,
        description: "LaunchDarkly Credential to use",
        title: "LaunchDarkly access token",
      },
    },
    required: ["team_key", "kind", "member_keys", "launchdarkly_access_token"],
  },
  output_parameters: {
    properties: {
      name: {
        type: Schema.types.string,
        description: "Team name",
        title: "Team name",
      },
      key: {
        type: Schema.types.string,
        description: "Team key",
        title: "Team key",
      },
      comment: {
        type: Schema.types.string,
        description: "Update team members comment",
        title: "Update team members comment",
      },
      kind: {
        type: Schema.types.string,
        description: "Target operation type",
        title: "Target operation",
      },
    },
    required: ["name"],
  },
});
