/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import UpdateTargetSegment from "./update_target_segment.ts";

Deno.test("UpdateTargetSegment can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UpdateTargetSegment_slack_function",
    title: "Test UpdateTargetSegment",
    description: "This is a generated test to test UpdateTargetSegment",
  });
  testWorkflow.addStep(UpdateTargetSegment, {
    project_key: "test",
    environment_key: "test",
    segment_key: "test",
    kind: "test",
    context_kind_key: "test",
    target_key: "test",
    launchdarkly_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(
    actual.function_id,
    "A05RF94AFB3#/functions/update_target_segment",
  );
  assertEquals(actual.inputs, {
    project_key: "test",
    environment_key: "test",
    segment_key: "test",
    kind: "test",
    context_kind_key: "test",
    target_key: "test",
    launchdarkly_access_token: "test",
  });
});

Deno.test("All outputs of Slack function UpdateTargetSegment should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UpdateTargetSegment_slack_function",
    title: "Test UpdateTargetSegment",
    description: "This is a generated test to test UpdateTargetSegment",
  });
  const step = testWorkflow.addStep(UpdateTargetSegment, {
    project_key: "test",
    environment_key: "test",
    segment_key: "test",
    kind: "test",
    context_kind_key: "test",
    target_key: "test",
    launchdarkly_access_token: "test",
  });
  assertExists(step.outputs.name);
  assertExists(step.outputs.description);
  assertExists(step.outputs.key);
  assertExists(step.outputs.environment_key);
  assertExists(step.outputs.comment);
  assertExists(step.outputs.kind);
});
