/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import UpdateTargetFeatureFlag from "./update_target_feature_flag.ts";

Deno.test("UpdateTargetFeatureFlag can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UpdateTargetFeatureFlag_slack_function",
    title: "Test UpdateTargetFeatureFlag",
    description: "This is a generated test to test UpdateTargetFeatureFlag",
  });
  testWorkflow.addStep(UpdateTargetFeatureFlag, {
    project_key: "test",
    feature_flag_key: "test",
    environment_key: "test",
    variation_id: "test",
    kind: "test",
    target_key: "test",
    launchdarkly_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(
    actual.function_id,
    "A05RF94AFB3#/functions/update_target_feature_flag",
  );
  assertEquals(actual.inputs, {
    project_key: "test",
    feature_flag_key: "test",
    environment_key: "test",
    variation_id: "test",
    kind: "test",
    target_key: "test",
    launchdarkly_access_token: "test",
  });
});

Deno.test("All outputs of Slack function UpdateTargetFeatureFlag should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_UpdateTargetFeatureFlag_slack_function",
    title: "Test UpdateTargetFeatureFlag",
    description: "This is a generated test to test UpdateTargetFeatureFlag",
  });
  const step = testWorkflow.addStep(UpdateTargetFeatureFlag, {
    project_key: "test",
    feature_flag_key: "test",
    environment_key: "test",
    variation_id: "test",
    kind: "test",
    target_key: "test",
    launchdarkly_access_token: "test",
  });
  assertExists(step.outputs.name);
  assertExists(step.outputs.description);
  assertExists(step.outputs.key);
  assertExists(step.outputs.environment_key);
  assertExists(step.outputs.comment);
  assertExists(step.outputs.kind);
});
