/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateTask from "./create_task.ts";

Deno.test("CreateTask can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateTask_slack_function",
    title: "Test CreateTask",
    description: "This is a generated test to test CreateTask",
  });
  testWorkflow.addStep(CreateTask, { incident_id: "test", title: "test" });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05TG2LEXPV#/functions/create_task");
  assertEquals(actual.inputs, { incident_id: "test", title: "test" });
});

Deno.test("All outputs of Slack function CreateTask should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateTask_slack_function",
    title: "Test CreateTask",
    description: "This is a generated test to test CreateTask",
  });
  const step = testWorkflow.addStep(CreateTask, {
    incident_id: "test",
    title: "test",
  });
  assertExists(step.outputs.task_id);
  assertExists(step.outputs.task_description);
  assertExists(step.outputs.title);
  assertExists(step.outputs.state);
});
