/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateIncident from "./create_incident.ts";

Deno.test("CreateIncident can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateIncident_slack_function",
    title: "Test CreateIncident",
    description: "This is a generated test to test CreateIncident",
  });
  testWorkflow.addStep(CreateIncident, { name: "test" });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05TG2LEXPV#/functions/create_incident");
  assertEquals(actual.inputs, { name: "test" });
});

Deno.test("All outputs of Slack function CreateIncident should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateIncident_slack_function",
    title: "Test CreateIncident",
    description: "This is a generated test to test CreateIncident",
  });
  const step = testWorkflow.addStep(CreateIncident, { name: "test" });
  assertExists(step.outputs.incident_id);
  assertExists(step.outputs.incident_url);
  assertExists(step.outputs.incident_description);
  assertExists(step.outputs.priority);
  assertExists(step.outputs.severity);
});
