/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import StartMeeting from "./start_meeting.ts";

Deno.test("StartMeeting can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_StartMeeting_slack_function",
    title: "Test StartMeeting",
    description: "This is a generated test to test StartMeeting",
  });
  testWorkflow.addStep(StartMeeting, { google_access_token: "test" });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05A1NP97K6#/functions/start_meeting");
  assertEquals(actual.inputs, { google_access_token: "test" });
});

Deno.test("All outputs of Slack function StartMeeting should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_StartMeeting_slack_function",
    title: "Test StartMeeting",
    description: "This is a generated test to test StartMeeting",
  });
  const step = testWorkflow.addStep(StartMeeting, {
    google_access_token: "test",
  });
  assertExists(step.outputs.name);
  assertExists(step.outputs.meeting_link);
});
