/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateTodoList from "./create_todo_list.ts";

Deno.test("CreateTodoList can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateTodoList_slack_function",
    title: "Test CreateTodoList",
    description: "This is a generated test to test CreateTodoList",
  });
  testWorkflow.addStep(CreateTodoList, {
    domain: "test",
    project_id: "test",
    name: "test",
    basecamp_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05UU55CFFA#/functions/create_todo_list");
  assertEquals(actual.inputs, {
    domain: "test",
    project_id: "test",
    name: "test",
    basecamp_access_token: "test",
  });
});

Deno.test("All outputs of Slack function CreateTodoList should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateTodoList_slack_function",
    title: "Test CreateTodoList",
    description: "This is a generated test to test CreateTodoList",
  });
  const step = testWorkflow.addStep(CreateTodoList, {
    domain: "test",
    project_id: "test",
    name: "test",
    basecamp_access_token: "test",
  });
  assertExists(step.outputs.id);
  assertExists(step.outputs.name);
  assertExists(step.outputs.url);
});
