/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05UU55CFFA#/functions/create_todo_list",
  title: "Create a to-do list",
  input_parameters: {
    properties: {
      domain: {
        type: Schema.types.string,
        description: "Select an account",
        title: "Account",
      },
      project_id: {
        type: Schema.types.string,
        description: "Select a project",
        title: "Project",
      },
      name: {
        type: Schema.types.string,
        description: "Enter text",
        title: "To-do list name",
      },
      description: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Description",
      },
      basecamp_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Basecamp access token",
      },
    },
    required: ["domain", "project_id", "name", "basecamp_access_token"],
  },
  output_parameters: {
    properties: {
      id: { type: Schema.types.string, title: "To-do list ID" },
      name: { type: Schema.types.string, title: "To-do list name" },
      url: { type: Schema.types.string, title: "To-do list URL" },
    },
    required: ["id", "name", "url"],
  },
});
