/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateTodo from "./create_todo.ts";

Deno.test("CreateTodo can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateTodo_slack_function",
    title: "Test CreateTodo",
    description: "This is a generated test to test CreateTodo",
  });
  testWorkflow.addStep(CreateTodo, {
    domain: "test",
    project_id: "test",
    todo_list_id: "test",
    content: "test",
    basecamp_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05UU55CFFA#/functions/create_todo");
  assertEquals(actual.inputs, {
    domain: "test",
    project_id: "test",
    todo_list_id: "test",
    content: "test",
    basecamp_access_token: "test",
  });
});

Deno.test("All outputs of Slack function CreateTodo should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateTodo_slack_function",
    title: "Test CreateTodo",
    description: "This is a generated test to test CreateTodo",
  });
  const step = testWorkflow.addStep(CreateTodo, {
    domain: "test",
    project_id: "test",
    todo_list_id: "test",
    content: "test",
    basecamp_access_token: "test",
  });
  assertExists(step.outputs.id);
  assertExists(step.outputs.content);
  assertExists(step.outputs.url);
});
