/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import MarkTodoComplete from "./mark_todo_complete.ts";

Deno.test("MarkTodoComplete can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_MarkTodoComplete_slack_function",
    title: "Test MarkTodoComplete",
    description: "This is a generated test to test MarkTodoComplete",
  });
  testWorkflow.addStep(MarkTodoComplete, {
    domain: "test",
    project_id: "test",
    todo_list_id: "test",
    todo_id: "test",
    basecamp_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05UU55CFFA#/functions/mark_todo_complete");
  assertEquals(actual.inputs, {
    domain: "test",
    project_id: "test",
    todo_list_id: "test",
    todo_id: "test",
    basecamp_access_token: "test",
  });
});

Deno.test("All outputs of Slack function MarkTodoComplete should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_MarkTodoComplete_slack_function",
    title: "Test MarkTodoComplete",
    description: "This is a generated test to test MarkTodoComplete",
  });
  const step = testWorkflow.addStep(MarkTodoComplete, {
    domain: "test",
    project_id: "test",
    todo_list_id: "test",
    todo_id: "test",
    basecamp_access_token: "test",
  });
  assertExists(step.outputs.id);
});
