/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateEnvelope from "./create_envelope.ts";

Deno.test("CreateEnvelope can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateEnvelope_slack_function",
    title: "Test CreateEnvelope",
    description: "This is a generated test to test CreateEnvelope",
  });
  testWorkflow.addStep(CreateEnvelope, {
    subdomain: "test",
    account_id: "test",
    template_id: "test",
    docusign_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05570UAVE0#/functions/create_envelope");
  assertEquals(actual.inputs, {
    subdomain: "test",
    account_id: "test",
    template_id: "test",
    docusign_access_token: "test",
  });
});

Deno.test("All outputs of Slack function CreateEnvelope should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateEnvelope_slack_function",
    title: "Test CreateEnvelope",
    description: "This is a generated test to test CreateEnvelope",
  });
  const step = testWorkflow.addStep(CreateEnvelope, {
    subdomain: "test",
    account_id: "test",
    template_id: "test",
    docusign_access_token: "test",
  });
  assertExists(step.outputs.envelope_id);
});
