/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import SendEnvelope from "./send_envelope.ts";

Deno.test("SendEnvelope can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_SendEnvelope_slack_function",
    title: "Test SendEnvelope",
    description: "This is a generated test to test SendEnvelope",
  });
  testWorkflow.addStep(SendEnvelope, {
    subdomain: "test",
    account_id: "test",
    template_id: "test",
    recipient_role: "test",
    recipient_name: "test",
    recipient_email: "test",
    docusign_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05570UAVE0#/functions/send_envelope");
  assertEquals(actual.inputs, {
    subdomain: "test",
    account_id: "test",
    template_id: "test",
    recipient_role: "test",
    recipient_name: "test",
    recipient_email: "test",
    docusign_access_token: "test",
  });
});

Deno.test("All outputs of Slack function SendEnvelope should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_SendEnvelope_slack_function",
    title: "Test SendEnvelope",
    description: "This is a generated test to test SendEnvelope",
  });
  const step = testWorkflow.addStep(SendEnvelope, {
    subdomain: "test",
    account_id: "test",
    template_id: "test",
    recipient_role: "test",
    recipient_name: "test",
    recipient_email: "test",
    docusign_access_token: "test",
  });
  assertExists(step.outputs.envelope_id);
});
