/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateEvent from "./create_event.ts";

const GoogleCalendar = { CreateEvent } as const;

export default GoogleCalendar;
