/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import GetMeetingLink from "./functions/get_meeting_link.ts";

const Calendly = { functions: { GetMeetingLink } } as const;

export default Calendly;
