/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CopyBoard from "./copy_board.ts";

Deno.test("CopyBoard can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CopyBoard_slack_function",
    title: "Test CopyBoard",
    description: "This is a generated test to test CopyBoard",
  });
  testWorkflow.addStep(CopyBoard, {
    board_id: "test",
    name: "test",
    description: "test",
    miro_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05NR1RGCBZ#/functions/copy_board");
  assertEquals(actual.inputs, {
    board_id: "test",
    name: "test",
    description: "test",
    miro_access_token: "test",
  });
});

Deno.test("All outputs of Slack function CopyBoard should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CopyBoard_slack_function",
    title: "Test CopyBoard",
    description: "This is a generated test to test CopyBoard",
  });
  const step = testWorkflow.addStep(CopyBoard, {
    board_id: "test",
    name: "test",
    description: "test",
    miro_access_token: "test",
  });
  assertExists(step.outputs.board_id);
  assertExists(step.outputs.link);
});
