/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateDocument from "./create_document.ts";

Deno.test("CreateDocument can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateDocument_slack_function",
    title: "Test CreateDocument",
    description: "This is a generated test to test CreateDocument",
  });
  testWorkflow.addStep(CreateDocument, {
    title: "test",
    product: "test",
    lucid_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A059SAQK6MC#/functions/create_document");
  assertEquals(actual.inputs, {
    title: "test",
    product: "test",
    lucid_access_token: "test",
  });
});

Deno.test("All outputs of Slack function CreateDocument should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateDocument_slack_function",
    title: "Test CreateDocument",
    description: "This is a generated test to test CreateDocument",
  });
  const step = testWorkflow.addStep(CreateDocument, {
    title: "test",
    product: "test",
    lucid_access_token: "test",
  });
  assertExists(step.outputs.title);
  assertExists(step.outputs.view_url);
  assertExists(step.outputs.edit_url);
  assertExists(step.outputs.product);
  assertExists(step.outputs.document_id);
});
