/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05T70HT5E1#/functions/create_workspace",
  title: "Create a workspace",
  input_parameters: {
    properties: {
      workspace_name: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Workspace name",
      },
      typeform_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Typeform access token",
      },
    },
    required: ["workspace_name", "typeform_access_token"],
  },
  output_parameters: {
    properties: {
      workspace_url: { type: Schema.types.string, title: "Workspace URL" },
      workspace_id: { type: Schema.types.string, title: "Workspace ID" },
      workspace_name: { type: Schema.types.string, title: "Workspace name" },
    },
    required: ["workspace_url", "workspace_id", "workspace_name"],
  },
});
