/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05T70HT5E1#/functions/get_form",
  title: "Get a form",
  input_parameters: {
    properties: {
      form_id: {
        type: Schema.types.string,
        description: "Select a form",
        title: "Select a form",
      },
      typeform_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Typeform access token",
      },
    },
    required: ["form_id", "typeform_access_token"],
  },
  output_parameters: {
    properties: {
      form: { type: Schema.types.object, title: "Form" },
      form_id: { type: Schema.types.string, title: "Form ID" },
      form_title: { type: Schema.types.string, title: "Form name" },
      form_url: { type: Schema.types.string, title: "Form display URL" },
      form_fields: {
        type: Schema.types.array,
        title: "Form fields",
        items: { type: undefined },
      },
    },
    required: [],
  },
});
