/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05T70HT5E1#/functions/get_form_insights",
  title: "Get form insights",
  description: "Retrieve form summary (works with Business or higher plans)",
  input_parameters: {
    properties: {
      form_id: {
        type: Schema.types.string,
        description: "Select a form",
        title: "Select a form",
      },
      typeform_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Typeform access token",
      },
    },
    required: ["form_id", "typeform_access_token"],
  },
  output_parameters: {
    properties: {
      summary: {
        type: Schema.types.object,
        title: "Form summary",
        properties: {
          average_time: { type: Schema.types.string, title: "Average time" },
          total_visits: { type: Schema.types.string, title: "Total visits" },
          unique_visits: { type: Schema.types.string, title: "Unique visits" },
          completion_rate: {
            type: Schema.types.string,
            title: "Completion rate",
          },
          responses_count: {
            type: Schema.types.string,
            title: "Response count",
          },
        },
        additionalProperties: true,
        required: [],
      },
      views_per_question: {
        type: Schema.types.object,
        title: "Views per question",
      },
      dropoffs_per_question: {
        type: Schema.types.object,
        title: "Drop-offs per question",
      },
    },
    required: [],
  },
});
