/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateSignRequest from "./functions/create_sign_request.ts";

const BoxSign = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/box.sign/create_sign_request CreateSignRequest} documentation.
     */
    CreateSignRequest,
  },
} as const;

export default BoxSign;
