/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateComment from "./functions/create_comment.ts";
import CreateProject from "./functions/create_project.ts";
import CreateTask from "./functions/create_task.ts";
import UpdateTask from "./functions/update_task.ts";

const Asana = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/asana/create_comment CreateComment} documentation.
     */
    CreateComment,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/asana/create_project CreateProject} documentation.
     */
    CreateProject,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/asana/create_task CreateTask} documentation.
     */
    CreateTask,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/asana/update_task UpdateTask} documentation.
     */
    UpdateTask,
  },
} as const;

export default Asana;
