/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A04U5QUE5EX#/functions/get_translated_gif",
  title: "Convert words to GIF",
  description:
    "GIPHY Translate converts words and phrases to the perfect GIF using GIPHY's special sauce algorithm",
  input_parameters: {
    properties: {
      search_term: {
        type: Schema.types.string,
        description: "Search query term or phrase",
        title: "Search term",
      },
      weirdness: {
        type: Schema.types.integer,
        description:
          "Value from 0-10 which makes results weirder as you go up the scale",
        title: "Weirdness",
      },
    },
    required: ["search_term"],
  },
  output_parameters: {
    properties: {
      web_url: {
        type: Schema.types.string,
        description: "A link to this GIF on giphy.com",
        title: "Web URL",
      },
      gif_url: {
        type: Schema.types.string,
        description:
          "The URL for the original version of this GIF that can be used for unfurling in Slack",
        title: "GIF URL",
      },
      title: {
        type: Schema.types.string,
        description: "The title of this GIF",
        title: "Title",
      },
    },
    required: ["web_url", "gif_url"],
  },
});
