/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CopyFile from "./functions/copy_file.ts";
import CreateFile from "./functions/create_file.ts";

const MicrosoftOnedrive = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/microsoft.onedrive/copy_file CopyFile} documentation.
     */
    CopyFile,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/microsoft.onedrive/create_file CreateFile} documentation.
     */
    CreateFile,
  },
} as const;

export default MicrosoftOnedrive;
