/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05MDPYMGJC#/functions/comment_on_a_folder",
  title: "Comment on a folder",
  input_parameters: {
    properties: {
      folder: { type: Schema.types.string, title: "Folder" },
      text: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Comment",
      },
      wrike_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Wrike credential to use",
        title: "Wrike Access Token",
      },
    },
    required: ["folder", "text", "wrike_access_token"],
  },
  output_parameters: {
    properties: {
      comment_id: {
        type: Schema.types.string,
        description: "The ID of the comment",
        title: "Comment ID",
      },
      author_id: {
        type: Schema.types.string,
        description: "The ID of the author",
        title: "Author ID",
      },
      text: {
        type: Schema.types.string,
        description: "The content of the comment",
        title: "Comment",
      },
      created_date: {
        type: Schema.types.string,
        description: "The date in which the comment was created",
        title: "Created date",
      },
      folder_id: {
        type: Schema.types.string,
        description: "The ID of the task",
        title: "Folder ID",
      },
    },
    required: ["comment_id", "author_id", "text", "created_date", "folder_id"],
  },
});
