/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05MDPYMGJC#/functions/create_a_task",
  title: "Create a task",
  input_parameters: {
    properties: {
      folder: { type: Schema.types.string, title: "Folder" },
      title: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Title",
      },
      description: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Description",
      },
      importance: {
        type: Schema.types.string,
        title: "Importance",
        enum: ["High", "Normal", "Low"],
      },
      assignees: {
        type: Schema.types.array,
        title: "Assignees",
        items: { type: Schema.types.string },
      },
      wrike_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Wrike credential to use",
        title: "Wrike Access Token",
      },
    },
    required: ["folder", "title", "wrike_access_token"],
  },
  output_parameters: {
    properties: {
      task_id: {
        type: Schema.types.string,
        description: "The ID of the task",
        title: "Task ID",
      },
      account_id: {
        type: Schema.types.string,
        description: "The ID of the account",
        title: "Account ID",
      },
      title: {
        type: Schema.types.string,
        description: "Title of the task",
        title: "Title",
      },
      description: {
        type: Schema.types.string,
        description: "Description of the task",
        title: "Description",
      },
      importance: {
        type: Schema.types.string,
        description: "Importance of the task",
        title: "Importance",
      },
    },
    required: ["task_id", "account_id", "title"],
  },
});
