/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05QS03T4MB#/functions/list_job_candidates",
  title: "List job candidates",
  description: "List all candidates for a job request",
  input_parameters: {
    properties: { job_id: { type: Schema.types.integer, title: "Job" } },
    required: ["job_id"],
  },
  output_parameters: {
    properties: {
      candidate_emails: {
        type: Schema.types.array,
        title: "Candidate emails",
        items: { type: Schema.types.string },
      },
      candidate_names: {
        type: Schema.types.array,
        title: "Candidates names",
        items: { type: Schema.types.string },
      },
    },
    required: [],
  },
});
