/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05QS03T4MB#/functions/reject_application",
  title: "Reject Application",
  input_parameters: {
    properties: {
      candidate_id: { type: Schema.types.integer, title: "Candidate email" },
      application_id: { type: Schema.types.integer, title: "Application" },
      rejection_reason_id: {
        type: Schema.types.integer,
        title: "Rejection reason",
      },
      notes: { type: Schema.types.string, title: "Notes" },
    },
    required: ["candidate_id", "application_id"],
  },
  output_parameters: {
    properties: {
      id: { type: Schema.types.integer, title: "Application ID" },
      status: { type: Schema.types.string, title: "Status" },
      candidate_id: { type: Schema.types.integer, title: "Candidate ID" },
    },
    required: [],
  },
});
