/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateIssue from "./functions/create_issue.ts";

const AtlassianJiraDataCenter = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/atlassian.jira-data-center/create_issue CreateIssue} documentation.
     */
    CreateIssue,
  },
} as const;

export default AtlassianJiraDataCenter;
