/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import FetchEmployees from "./fetch_employees.ts";

Deno.test("FetchEmployees can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_FetchEmployees_slack_function",
    title: "Test FetchEmployees",
    description: "This is a generated test to test FetchEmployees",
  });
  testWorkflow.addStep(FetchEmployees, { employment_status: "test" });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05RY71E6UE#/functions/fetch_employees");
  assertEquals(actual.inputs, { employment_status: "test" });
});

Deno.test("All outputs of Slack function FetchEmployees should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_FetchEmployees_slack_function",
    title: "Test FetchEmployees",
    description: "This is a generated test to test FetchEmployees",
  });
  const step = testWorkflow.addStep(FetchEmployees, {
    employment_status: "test",
  });
  assertExists(step.outputs.emails);
  assertExists(step.outputs.names);
  assertExists(step.outputs.employee_ids);
});
