/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05RY71E6UE#/functions/fetch_employees",
  title: "Fetch employees",
  input_parameters: {
    properties: {
      employment_status: {
        type: Schema.types.string,
        title: "Employment status",
      },
    },
    required: ["employment_status"],
  },
  output_parameters: {
    properties: {
      emails: {
        type: Schema.types.array,
        title: "Email IDs",
        items: { type: Schema.types.string },
      },
      names: {
        type: Schema.types.array,
        title: "Names",
        items: { type: Schema.types.string },
      },
      employee_ids: {
        type: Schema.types.array,
        title: "Employee IDs",
        items: { type: Schema.types.string },
      },
    },
    required: [],
  },
});
