/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import SendSms from "./functions/send_sms.ts";

const Ringcentral = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/ringcentral/send_sms SendSms} documentation.
     */
    SendSms,
  },
} as const;

export default Ringcentral;
