/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateApprovalRequestUpdateFlag from "./functions/create_approval_request_update_flag.ts";
import CreateFeatureFlag from "./functions/create_feature_flag.ts";
import UpdateFeatureFlagState from "./functions/update_feature_flag_state.ts";
import UpdateTargetFeatureFlag from "./functions/update_target_feature_flag.ts";
import UpdateTargetSegment from "./functions/update_target_segment.ts";

const Launchdarkly = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/launchdarkly/create_approval_request_update_flag CreateApprovalRequestUpdateFlag} documentation.
     */
    CreateApprovalRequestUpdateFlag,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/launchdarkly/create_feature_flag CreateFeatureFlag} documentation.
     */
    CreateFeatureFlag,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/launchdarkly/update_feature_flag_state UpdateFeatureFlagState} documentation.
     */
    UpdateFeatureFlagState,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/launchdarkly/update_target_feature_flag UpdateTargetFeatureFlag} documentation.
     */
    UpdateTargetFeatureFlag,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/launchdarkly/update_target_segment UpdateTargetSegment} documentation.
     */
    UpdateTargetSegment,
  },
} as const;

export default Launchdarkly;
