/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A060Q1RQSCE#/functions/send_signature_request_with_template",
  title: "Send signature request using a template",
  input_parameters: {
    properties: {
      title: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Title of the request",
      },
      template_id: {
        type: Schema.types.string,
        description: "Please select an option",
        title: "Template",
      },
      signer_role: {
        type: Schema.types.string,
        description: "Please select an option",
        title: "Signer role",
      },
      signer_name: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Signer name",
      },
      signer_email_address: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Signer email",
      },
      email_subject: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Email subject",
      },
      email_message: {
        type: Schema.types.string,
        description: "Enter text",
        title: "Email message",
      },
      dropbox_sign_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Dropbox Sign Credential to use",
        title: "Dropbox Sign access token",
      },
    },
    required: [
      "template_id",
      "signer_role",
      "signer_name",
      "signer_email_address",
      "dropbox_sign_access_token",
    ],
  },
  output_parameters: {
    properties: {
      signature_request_id: {
        type: Schema.types.string,
        description: "Signature request ID",
        title: "Signature request ID",
      },
      title: {
        type: Schema.types.string,
        description: "Signature request title",
        title: "Signature request title",
      },
      subject: {
        type: Schema.types.string,
        description: "Email subject",
        title: "Email subject",
      },
      message: {
        type: Schema.types.string,
        description: "Email message",
        title: "Email message",
      },
      signing_url: {
        type: Schema.types.string,
        description: "Signature signing URL",
        title: "Signature signing URL",
      },
      details_url: {
        type: Schema.types.string,
        description: "Signature details URL",
        title: "Signature details URL",
      },
      signer_name: {
        type: Schema.types.string,
        description: "Signer name",
        title: "Signer name",
      },
      signer_email_address: {
        type: Schema.types.string,
        description: "Signature request title",
        title: "Signature request title",
      },
    },
    required: [
      "signature_request_id",
      "signing_url",
      "details_url",
      "signer_name",
      "signer_email_address",
    ],
  },
});
