/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05S54578AE#/functions/update_task",
  title: "Update a task in a folder",
  input_parameters: {
    properties: {
      team_id: { type: Schema.types.integer, title: "Team" },
      space_id: { type: Schema.types.integer, title: "Space" },
      folder_id: { type: Schema.types.integer, title: "Folder" },
      list_id: { type: Schema.types.integer, title: "List" },
      task_id: { type: Schema.types.string, title: "Task to update" },
      name: { type: Schema.types.string, title: "Task name" },
      description: { type: Schema.types.string, title: "Description" },
      status: { type: Schema.types.string, title: "Status" },
      clickup_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Clickup Access Token",
      },
    },
    required: [
      "team_id",
      "space_id",
      "folder_id",
      "list_id",
      "task_id",
      "clickup_access_token",
    ],
  },
  output_parameters: {
    properties: {
      task_id: { type: Schema.types.string, title: "Task ID" },
      task_name: { type: Schema.types.string, title: "Task name" },
      start_date: { type: Schema.types.string, title: "Start at" },
      due_date: { type: Schema.types.string, title: "Due at" },
      description: { type: Schema.types.string, title: "Description" },
      date_created: { type: Schema.types.string, title: "Created at" },
      url: { type: Schema.types.string, title: "Link to task" },
      status: { type: Schema.types.string, title: "Task status" },
    },
    required: ["task_name", "url", "status"],
  },
});
