/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A04T6GE3LEB#/functions/edit_issue",
  title: "Edit an Issue",
  description: "Edit a JIRA Cloud issue",
  input_parameters: {
    properties: {
      atlassian_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Atlassian Access Token",
      },
      jira_domain: { type: Schema.types.string, title: "Jira domain" },
      project: { type: Schema.types.string, title: "Project" },
      issue_id: {
        type: Schema.types.string,
        description: "Issue ID",
        title: "Issue ID",
      },
      priority: {
        type: Schema.types.string,
        description: "Select an option...",
        title: "Priority",
      },
      assignee: {
        type: Schema.types.string,
        description: "Select an option...",
        title: "Assignee",
      },
      summary: {
        type: Schema.types.string,
        description: "Summary of the bug or issue ...",
        title: "Summary",
      },
      description: {
        type: Schema.types.string,
        description: "Description of the bug or issue ...",
        title: "Description",
      },
    },
    required: [
      "atlassian_access_token",
      "jira_domain",
      "project",
      "issue_id",
      "summary",
    ],
  },
  output_parameters: {
    properties: {
      response: {
        type: Schema.types.string,
        description: "Response",
        title: "Response",
      },
      project: {
        type: Schema.types.string,
        description: "Project",
        title: "Project",
      },
      issue_id: {
        type: Schema.types.string,
        description: "Issue ID",
        title: "Issue ID",
      },
      summary: {
        type: Schema.types.string,
        description: "Summary",
        title: "Summary",
      },
      description: {
        type: Schema.types.string,
        description: "Description",
        title: "Description",
      },
    },
    required: ["response"],
  },
});
