/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import GetEventLink from "./get_event_link.ts";

Deno.test("GetEventLink can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_GetEventLink_slack_function",
    title: "Test GetEventLink",
    description: "This is a generated test to test GetEventLink",
  });
  testWorkflow.addStep(GetEventLink, {
    calendly_user: "test",
    event_type: "test",
    calendly_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A050MUYMYFP#/functions/get_event_link");
  assertEquals(actual.inputs, {
    calendly_user: "test",
    event_type: "test",
    calendly_access_token: "test",
  });
});

Deno.test("All outputs of Slack function GetEventLink should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_GetEventLink_slack_function",
    title: "Test GetEventLink",
    description: "This is a generated test to test GetEventLink",
  });
  const step = testWorkflow.addStep(GetEventLink, {
    calendly_user: "test",
    event_type: "test",
    calendly_access_token: "test",
  });
  assertExists(step.outputs.scheduling_link);
});
