/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import GetMeetingLink from "./get_meeting_link.ts";

Deno.test("GetMeetingLink can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_GetMeetingLink_slack_function",
    title: "Test GetMeetingLink",
    description: "This is a generated test to test GetMeetingLink",
  });
  testWorkflow.addStep(GetMeetingLink, {
    calendly_user: "test",
    event_type: "test",
    calendly_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A050MUYMYFP#/functions/get_meeting_link");
  assertEquals(actual.inputs, {
    calendly_user: "test",
    event_type: "test",
    calendly_access_token: "test",
  });
});

Deno.test("All outputs of Slack function GetMeetingLink should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_GetMeetingLink_slack_function",
    title: "Test GetMeetingLink",
    description: "This is a generated test to test GetMeetingLink",
  });
  const step = testWorkflow.addStep(GetMeetingLink, {
    calendly_user: "test",
    event_type: "test",
    calendly_access_token: "test",
  });
  assertExists(step.outputs.meeting_link);
});
