/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A050MUYMYFP#/functions/get_event_link",
  title: "Get Calendly Meeting Link",
  description: "This step gets a Calendly meeting link by event type",
  input_parameters: {
    properties: {
      calendly_user: { type: Schema.types.string, title: "Calendly User" },
      event_type: { type: Schema.types.string, title: "Event Type" },
      calendly_access_token: {
        type: Schema.slack.types.oauth2,
        description: "Calendly credential to use",
        title: "Calendly Access Token",
      },
    },
    required: ["calendly_user", "event_type", "calendly_access_token"],
  },
  output_parameters: {
    properties: {
      scheduling_link: {
        type: Schema.types.string,
        description: "A Calendly meeting link for sharing",
        title: "Calendly Meeting Link",
      },
    },
    required: ["scheduling_link"],
  },
});
