/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import ArchiveBoard from "./functions/archive_board.ts";
import CreateBoard from "./functions/create_board.ts";
import CreateGroup from "./functions/create_group.ts";
import CreateItem from "./functions/create_item.ts";

const Monday = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/monday/archive_board ArchiveBoard} documentation.
     */
    ArchiveBoard,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/monday/create_board CreateBoard} documentation.
     */
    CreateBoard,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/monday/create_group CreateGroup} documentation.
     */
    CreateGroup,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/monday/create_item CreateItem} documentation.
     */
    CreateItem,
  },
} as const;

export default Monday;
