/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateIssue from "./create_issue.ts";

Deno.test("CreateIssue can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateIssue_slack_function",
    title: "Test CreateIssue",
    description: "This is a generated test to test CreateIssue",
  });
  testWorkflow.addStep(CreateIssue, {
    jira_data_center_access_token: "test",
    project: "test",
    issue_type: "test",
    summary: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A08FY679V53#/functions/create_issue");
  assertEquals(actual.inputs, {
    jira_data_center_access_token: "test",
    project: "test",
    issue_type: "test",
    summary: "test",
  });
});

Deno.test("All outputs of Slack function CreateIssue should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateIssue_slack_function",
    title: "Test CreateIssue",
    description: "This is a generated test to test CreateIssue",
  });
  const step = testWorkflow.addStep(CreateIssue, {
    jira_data_center_access_token: "test",
    project: "test",
    issue_type: "test",
    summary: "test",
  });
  assertExists(step.outputs.issue_id);
  assertExists(step.outputs.issue_url);
  assertExists(step.outputs.project);
  assertExists(step.outputs.summary);
  assertExists(step.outputs.description);
});
