/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { assertEquals, assertExists } from "../../../dev_deps.ts";
import { DefineWorkflow } from "../../../dev_deps.ts";
import CreateArticle from "./create_article.ts";

Deno.test("CreateArticle can be used as a Slack function in a workflow step", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateArticle_slack_function",
    title: "Test CreateArticle",
    description: "This is a generated test to test CreateArticle",
  });
  testWorkflow.addStep(CreateArticle, {
    title: "test",
    description: "test",
    body: "test",
    author_id: "test",
    state: "test",
    intercom_access_token: "test",
  });
  const actual = testWorkflow.steps[0].export();

  assertEquals(actual.function_id, "A05S4UJGUQK#/functions/create_article");
  assertEquals(actual.inputs, {
    title: "test",
    description: "test",
    body: "test",
    author_id: "test",
    state: "test",
    intercom_access_token: "test",
  });
});

Deno.test("All outputs of Slack function CreateArticle should exist", () => {
  const testWorkflow = DefineWorkflow({
    callback_id: "test_CreateArticle_slack_function",
    title: "Test CreateArticle",
    description: "This is a generated test to test CreateArticle",
  });
  const step = testWorkflow.addStep(CreateArticle, {
    title: "test",
    description: "test",
    body: "test",
    author_id: "test",
    state: "test",
    intercom_access_token: "test",
  });
  assertExists(step.outputs.article_id);
  assertExists(step.outputs.title);
  assertExists(step.outputs.description);
  assertExists(step.outputs.body);
  assertExists(step.outputs.state);
});
