/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import { DefineConnector } from "../../../deps.ts";
import { Schema } from "../../../deps.ts";

export default DefineConnector({
  callback_id: "A05S4UJGUQK#/functions/create_ticket",
  title: "Create a ticket",
  input_parameters: {
    properties: {
      title: {
        type: Schema.types.string,
        description: "Enter title",
        title: "Title",
      },
      description: {
        type: Schema.types.string,
        description: "Enter description",
        title: "Description",
      },
      ticket_type_id: { type: Schema.types.string, title: "Ticket type" },
      contact_email: {
        type: Schema.types.string,
        description: "Enter email ID",
        title: "Email",
      },
      intercom_access_token: {
        type: Schema.slack.types.oauth2,
        title: "Intercom access token",
      },
    },
    required: [
      "title",
      "description",
      "ticket_type_id",
      "contact_email",
      "intercom_access_token",
    ],
  },
  output_parameters: {
    properties: {
      ticket_id: { type: Schema.types.string, title: "Ticket ID" },
      title: { type: Schema.types.string, title: "Title" },
      description: { type: Schema.types.string, title: "Description" },
      ticket_type: {
        type: Schema.types.object,
        title: "Ticket type",
        properties: {
          name: { type: Schema.types.string },
          archived: { type: Schema.types.boolean },
          created_at: { type: Schema.types.string },
          updated_at: { type: Schema.types.string },
          description: { type: Schema.types.string },
        },
        additionalProperties: true,
        required: [],
      },
    },
    required: [],
  },
});
