/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateIncident from "./functions/create_incident.ts";
import GetIncident from "./functions/get_incident.ts";
import UpdateIncident from "./functions/update_incident.ts";

const Servicenow = {
  functions: {
    /**
     * @see The {@link https://api.slack.com/reference/connectors/servicenow/create_incident CreateIncident} documentation.
     */
    CreateIncident,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/servicenow/get_incident GetIncident} documentation.
     */
    GetIncident,
    /**
     * @see The {@link https://api.slack.com/reference/connectors/servicenow/update_incident UpdateIncident} documentation.
     */
    UpdateIncident,
  },
} as const;

export default Servicenow;
