/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import GetRandomGif from "./functions/get_random_gif.ts";
import GetTranslatedGif from "./functions/get_translated_gif.ts";

const Giphy = { functions: { GetRandomGif, GetTranslatedGif } } as const;

export default Giphy;
