/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import GetRandomGif from "./get_random_gif.ts";
import GetTranslatedGif from "./get_translated_gif.ts";

const Giphy = { GetRandomGif, GetTranslatedGif } as const;

export default Giphy;
